Fixed incomplete database setup
The "postgres_create_db()" function incorrectly returns a non-zero
value when the database is created successfully.  This in turn
causes the security and node-manager scripts to terminate the rest
of their database setup.  On the IDP node, this was mitigated by the
fact that the node-manager is setup (and then later removed) first
where the database is initially created and then the security
setup script was able to run to completion.

diff --git a/esg-functions b/esg-functions
--- a/esg-functions
+++ b/esg-functions
@@ -705,14 +705,16 @@ check_tomcat_process() {
 #----------------------------------------------------------
 postgres_create_db() {
     # Creates a database if it does not already exist
+    local rc=0
     if [ -z "$(postgres_list_dbs ${1})" ] ; then
         #Create the database...
         echo "Creating ESGF database: [${1}]"
-        PGPASSWORD=${PGPASSWORD:-${pg_sys_acct_passwd}} createdb ${1} >& /dev/null
-        (( $? > 1 )) && echo " ERROR: Could not create esgf node database: ${node_db_name}" && return $?
+        PGPASSWORD=${PGPASSWORD:-${pg_sys_acct_passwd}} createdb ${1} >& /dev/null || rc=$?
+        [ ${rc} -ne 0 ] && echo " ERROR: Could not create esgf node database: ${node_db_name}"
     else
         echo "ESGF database [${1}] already exists, not creating."
     fi
+    return ${rc}
 }
 
 postgres_list_db_schemas() {
