Fix: Have to make sure the tomcat group exists before attempting to chgrp a file to it

diff --git a/esg-node b/esg-node
--- a/esg-node
+++ b/esg-node
@@ -1189,8 +1189,11 @@ setup_esgcet() {
     echo "chown -R ${installer_uid}:${installer_gid} $HOME/.esgcet"
     chown -R ${installer_uid}:${installer_gid} $HOME/.esgcet 
     [ $? != 0 ] && echo "**WARNING**: Could not change owner successfully - this will lead to inability to use the publisher properly!"
+    #Let's make sure the group is there before we attempt to assign a file to it....
+    /usr/sbin/groupadd -r -f ${tomcat_group}
+    [ $? != 0 ] && [ $? != 9 ] && echo "ERROR: *Could not add tomcat system group: ${tomcat_group}" && popd && checked_done 1
     chgrp ${tomcat_group} ${HOME}/.esgcet/esg.ini && chmod 640 ${HOME}/.esgcet/esg.ini && chmod 755 ${HOME}
-    [ $? != 0 ] && echo "**WARNING**: Could not change owner successfully - this will lead to inability to use the publisher properly!"
+    [ $? != 0 ] && echo "**WARNING**: Could not change group successfully - this will lead to inability to use the publisher properly!"
     start_postgress
 
     if [ "${mode}" = "U" ]; then
@@ -1354,10 +1357,8 @@ setup_tomcat() {
     if [ $? != 0 ]; then 
         echo " WARNING: There is no tomcat user \"$tomcat_user\" present on system"
         #NOTE: "useradd/groupadd" are a RedHat/CentOS thing... to make this cross distro compatible clean this up.
-        if (id -g ${tomcat_group} >& /dev/null); then
-            /usr/sbin/groupadd -r -f ${tomcat_group}
-            [ $? != 0 ] && [ $? != 9 ] && echo "ERROR: Could not add tomcat system group: ${tomcat_group}" && popd && checked_done 1
-        fi
+        /usr/sbin/groupadd -r -f ${tomcat_group}
+        [ $? != 0 ] && [ $? != 9 ] && echo "ERROR: Could not add tomcat system group: ${tomcat_group}" && popd && checked_done 1
         /usr/sbin/useradd -r -c"Tomcat Server Identity" -g $tomcat_group $tomcat_user
         [ $? != 0 ] && [ $? != 9 ] && echo "ERROR: Could not add tomcat system account user \"$tomcat_user\"" && popd && checked_done 1
     fi
