no need to popd when there was no pushd - generates error for no reason

diff --git a/esg-node b/esg-node
--- a/esg-node
+++ b/esg-node
@@ -1295,7 +1295,7 @@ start_postgress() {
     check_shmmax
     echo "su $pg_sys_acct -c \"$postgress_install_dir/bin/pg_ctl -D $postgress_install_dir/data start\""
     PGPASSWORD=${PGPASSWORD:-${pg_sys_acct_passwd:-${security_admin_password}}} su $pg_sys_acct -c "$postgress_install_dir/bin/pg_ctl -D $postgress_install_dir/data start"
-    [ $? != 0 ] && echo " ERROR: Could not start database!" && popd && return 1
+    [ $? != 0 ] && echo " ERROR: Could not start database!" && return 1
 
     #NOTE: How long does it take for the database to come up? Set sleep appropriately
     echo "Giving database time to startup... (3 seconds) "
