New startup hooks: Making sure permissions are set apprpriately for publisher and TDS [THREDDS] content

diff --git a/esg-node b/esg-node
--- a/esg-node
+++ b/esg-node
@@ -1825,6 +1825,13 @@ test_esgcet() {
     checked_done 0
 }
 
+esgcet_setup_hook() {
+    echo -n "ESGCET (Publisher) Startup Hook: Setting perms... "
+    [ ! -e ${publisher_home}/${publisher_config} ] && echo " Could not find publisher configuration file [${publisher_home}/${publisher_config}] :-(" && return 1
+    chgrp ${tomcat_group} ${publisher_home}/${publisher_config} && chmod 644 ${publisher_home}/${publisher_config} && chmod 755 ${HOME}
+    [ $? != 0 ] && echo ":-/" && return 2
+}
+
 #####
 # Apache Tomcat
 # arg 1 -> The password for the current keystore
@@ -2892,7 +2899,7 @@ setup_tds() {
     if [ ! -d ${thredds_content_dir}/thredds ] || ((force_install)); then
         mkdir -p ${thredds_content_dir}/thredds
         cp -R ${tomcat_install_dir}/webapps/thredds/WEB-INF/altContent/startup/public ${thredds_content_dir}/thredds
-        chown -R ${tomcat_user}:${tomcat_group} ${thredds_content_dir}
+        chown -R ${tomcat_user} ${thredds_content_dir}
         chmod -R 755 ${thredds_content_dir}
         created_brand_new_thredds_content_dir=1
     fi
@@ -3008,6 +3015,12 @@ test_tds() {
     checked_done 0
 }
 
+tds_startup_hook() {
+    echo -n "TDS (THREDDS) Startup Hook: Setting perms... "
+    chown -R ${tomcat_user} ${thredds_content_dir}
+    [ $? != 0 ] && echo ":-(" && return 1
+    echo ":-)"
+}
 
 #####
 # Globus Toolkit ->  MyProxy (client) & GridFTP (server)
@@ -5531,6 +5544,8 @@ show_svc_list() {
 #In the submodule script the convention is <module>_startup_hook() (where module does not contain esg(f) prefix)
 run_startup_hooks() {
     echo "Running startup hooks..."
+    ( escet_setup_hook )
+    ( tds_startup_hook )
     (source ${scripts_dir}/esg-orp >& /dev/null && orp_startup_hook)
     (source ${scripts_dir}/esg-security >& /dev/null && security_startup_hook)
     (source ${scripts_dir}/esg-web-fe >& /dev/null && web_fe_startup_hook)
