Clean up...
Changed order of installation inititialization so that properties are
not looked for until they need to be.
Lots more lil things, look at the diff for details

diff --git a/esg-node b/esg-node
--- a/esg-node
+++ b/esg-node
@@ -98,7 +98,7 @@ init() {
     debug_print "esg-node initilizing..."
 
     #--------------------------------
-    # Internal data-node code versions and supporting external libraries
+    # Internal data-node code versions
     #--------------------------------
     #cdat_version=${cdat_version:-"eb8b668"}
     cdat_version=${cdat_version:-"6.0.alpha"}
@@ -109,18 +109,20 @@ init() {
     esgf_node_manager_db_version=${esgf_node_manager_db_version:-"0.1.5"}
 
     #see esg-orp project:
-    esg_orp_version=${esg_orp_version:-"1.0.4"}
+    esg_orp_version=${esg_orp_version:-"1.1.0"}
 
     #see esgf-security project:
-    esgf_security_version=${esgf_security_version:-"1.2.7"}
+    esgf_security_version=${esgf_security_version:-"1.2.8"}
     esgf_security_db_version=${esgf_security_db_version:-"0.1.4"}
-    opensaml_version=${opensaml_version:-"2.3.2"}
-    openws_version=${openws_version:-"1.3.1"}
-    xmltooling_version=${xmltooling_version:-"1.2.2"}
-    xsgroup_role_version=${xsgroup_role_version:-"1.0.0"}
 
     #see esgf-idp project:
     esgf_idp_version=${esgf_idp_version:-"1.1.4"}
+
+    #see esg-search project:
+    esg_search_version=${esg_search_version:-"1.1.1"}
+
+    #see esgf-web-fe project:
+    esgf_web_fe_version=${esgf_web_fe_version:-"0.9.6"}
     
     #--------------------------------
     # External programs' versions
@@ -162,7 +164,6 @@ init() {
     gateway_service_root=${ESGF_PEER_SVC_ROOT}
     myproxy_endpoint=${myproxy_endpoint:-${gateway_service_root%%/*}}
     myproxy_port=${myproxy_port:-7512}
-    esg_root_id=${ESG_ROOT_ID:-$(echo `hostname -s`.`hostname --domain` | awk -F. ' {print $(NF-1)} ')}
     mail_smtp_host=${mail_smtp_host:-smtp.`hostname --domain`} #standard guess.
     mail_admin_address=${mail_admin_address}
 
@@ -278,12 +279,42 @@ init() {
     default_dname="OU=simpleCA-pcmdi3.llnl.gov, OU=GlobusTest, O=Grid" #zoiks: allow this to be empty to allow prompting of user for fields!
     config_file=${esg_config_dir}/esgf.properties
 
+}
+
+init_structure() {
+
+    #--------------
+    #Prepare necessary support filesystem structure and files
+    #--------------
+
+    mkdir -p ${scripts_dir}
+    [ $? != 0 ] && echo "ERROR: could not create ${scripts_dir}... required for installation" && checked_done 1
+
+    mkdir -p ${esg_backup_dir}	&& \
+	mkdir -p ${esg_tools_dir} && \
+	mkdir -p ${esg_log_dir} && \
+	mkdir -p ${esg_config_dir} && \
+	mkdir -p ${esg_etc_dir} && \
+	mkdir -p ${tomcat_conf_dir} && \
+	touch ${config_file}
+    [ $? != 0 ] && echo "ERROR: could not create ${esg_root_dir} dir and/or subdirectories" && checked_done 1
+
+    chmod 777 ${esg_etc_dir}
+
+    [ -w "${envfile}" ] && write_paths
+
+    #--------------
+    #Setup variables....
+    #--------------
 
     esgf_host=${esgf_host}
     [ -z "${esgf_host}" ] && get_property esgf_node $(hostname --fqdn)
 
     esgf_default_peer=${esgf_default_peer:-${ESGF_DEFAULT_PEER}}
     [ -z "${esgf_default_peer}" ] && get_property esgf_default_peer
+
+    esg_root_id=${esg_root_id:-${ESGF_ROOT_ID}}
+    [ -z "${esg_root_id}" ] && get_property esg_root_id
 
     #NOTE: Calls to get_property must be made AFTER we touch the file ${config_file} to make sure it exists
     #this is actually an issue with dedup_properties that gets called in the get_property function
@@ -306,28 +337,6 @@ init() {
     export ESGINI=${publisher_home}/${publisher_config}
     ((DEBUG)) && echo "ESGINI = ${ESGINI}"
 
-}
-
-init_structure() {
-    #--------------
-    #Prepare necessary support filesystem structure and files
-    #--------------
-
-    mkdir -p ${scripts_dir}
-    [ $? != 0 ] && echo "ERROR: could not create ${scripts_dir}... required for installation" && checked_done 1
-
-    mkdir -p ${esg_backup_dir}	&& \
-	mkdir -p ${esg_tools_dir} && \
-	mkdir -p ${esg_log_dir} && \
-	mkdir -p ${esg_config_dir} && \
-	mkdir -p ${esg_etc_dir} && \
-	mkdir -p ${tomcat_conf_dir} && \
-	touch ${config_file}
-    [ $? != 0 ] && echo "ERROR: could not create ${esg_root_dir} dir and/or subdirectories" && checked_done 1
-
-    chmod 777 ${esg_etc_dir}
-
-    [ -w "${envfile}" ] && write_paths
     return 0
 }
 
@@ -4450,8 +4459,9 @@ initial_setup_questionnaire() {
     if [ -z "${esg_root_id}" ] || ((force_install)); then
 	while [ 1 ]; do
 	    unset input
-	    read -p "What is the name of your organization? [${esg_root_id}]: " input
-	    [ -z "${input}" ] && [ -n "${esg_root_id}" ] && input=${esg_root_id} && break
+            default=$(echo `hostname -s`.`hostname --domain` | awk -F. ' {print $(NF-1)} ')
+	    read -p "What is the name of your organization? [${default}]: " input
+	    [ -z "${input}" ] && esg_root_id=${default} && write_as_property esg_root_id && break
 	    [ -n "${input}" ] && esg_root_id=$(echo ${input} | sed 's/ /_/g') && write_as_property esg_root_id && break
 	done
     else
@@ -4564,7 +4574,7 @@ esgf_node_info() {
      This is required for publication.
 
      ESGF Node:
-     ---------
+      ---------
      |Tomcat   |
      |-Node Mgr|
      |-Thredds |
@@ -4582,7 +4592,7 @@ esgf_node_info() {
      |(Virtual)|
      | Machine |
      |---------|
-     ---------
+      ---------
 
      -ESG \n\n" | more 
     
@@ -4817,6 +4827,7 @@ main() {
 			shift
 		    done
 		    [ -z "${selection_string}" ] && echo "Unknown Node Type: [${tvalue}], Sorry :-(" && exit 1;
+                    [ ! -d ${esg_config_dir} ] && mkdir -p ${esg_config_dir} 
 		    echo "node type set to: [ $selection_string] (${sel}) "
 		    set_sel ${sel}
 		    exit 0
@@ -5193,7 +5204,6 @@ main() {
 	    exit 1
 	fi
 
-	init_structure
 	esgf_node_info
 
 	local doit="n"
@@ -5208,6 +5218,8 @@ main() {
 	if [ "${doit}" = "N" ] || [ "${doit}" = "n" ] || [ "${doit}" = "no" ]; then
 	    exit 0
 	fi    
+
+	init_structure
 
 	(( force_install ))  && echo "(force install is ON)"
 	(( (sel & DATA_BIT ) != 0))    && echo "(data node type selected)"
