shoring up database backup and restore functions

diff --git a/esg-node b/esg-node
--- a/esg-node
+++ b/esg-node
@@ -5033,23 +5033,42 @@ backup() {
 }
 
 backup_db() {
-    local my_node_db_name=${1:-${db_database}}
-    local my_schema_name=${2}
+    local my_node_db_name=${db_database}
+    local my_schema_name
+    
+    echo -n "backup_db: "
+    while [ -n "$1" ]; do
+        case ${1} in 
+            -s | --schema)
+                shift
+                my_schema_name=${1}
+                ;;
+            -db | --database)
+                shift
+                my_node_db_name=${1}
+                ;;
+        esac
+        shift
+    done
+    echo -n "database = [${my_node_db_name}] "
+    [ -n "${my_schema_name}" ] && echo -n "schema = [${my_schema_name}]"
+    echo
+
     mkdir -p ${esg_backup_dir}
     pushd ${esg_backup_dir} >& /dev/null
 
     start_postgress
 
-    echo "Backing up database: ${my_node_db_name} -to->	 ${my_node_db_name}_backup_$(date ${date_format}).sql"
-    PGPASSWORD=${PGPASSWORD:-${pg_sys_acct_passwd}} pg_dump -U ${postgress_user} ${my_node_db_name} > ${my_node_db_name}_backup_$(date ${date_format}).sql
-    [ $? == 0 ] && echo " [OK] " || (echo " [FAIL] " && return 1)
-
     #back up the schema specifically, if one is provided
     if [ -n "${my_schema_name}" ]; then
 	my_schema_name=_${my_schema_name}
-	echo "Backing up esgf schema esgf${my_schema_name} of ${my_node_db_name} -to-> ${my_node_db_name}_esgf${my_schema_name}_backup_$(date ${date_format}).sql"
-	PGPASSWORD=${PGPASSWORD:-${pg_sys_acct_passwd}} pg_dump -U ${postgress_user} --schema=esgf${my_schema_name} ${my_node_db_name} > ${my_node_db_name}_esgf_backup_$(date ${date_format}).sql
+	echo "Backing up esgf schema esgf_${my_schema_name} of ${my_node_db_name} -to-> ${my_node_db_name}_esgf_${my_schema_name}_backup_$(date ${date_format}).sql"
+	PGPASSWORD=${PGPASSWORD:-${pg_sys_acct_passwd}} pg_dump -U ${postgress_user} --schema=esgf_${my_schema_name} ${my_node_db_name} > ${my_node_db_name}_esgf_backup_$(date ${date_format}).sql
 	[ $? == 0 ] && echo " [OK] " || (echo " [FAIL] " && return 1)
+    else
+        echo "Backing up database: ${my_node_db_name} -to->	 ${my_node_db_name}_backup_$(date ${date_format}).sql"
+        PGPASSWORD=${PGPASSWORD:-${pg_sys_acct_passwd}} pg_dump -U ${postgress_user} ${my_node_db_name} > ${my_node_db_name}_backup_$(date ${date_format}).sql
+        [ $? == 0 ] && echo " [OK] " || (echo " [FAIL] " && return 1)
     fi
 
     #-------------
@@ -5070,8 +5089,26 @@ backup_db() {
 }
 
 restore_last_db_backup() {
-    local my_node_db_name=${1:-${db_database}}
-    local my_schema_name=${2}
+    local my_node_db_name=${db_database}
+    local my_schema_name
+    
+    echo -n "backup_db: "
+    while [ -n "$1" ]; do
+        case ${1} in 
+            -s | --schema)
+                shift
+                my_schema_name=${1}
+                ;;
+            -db | --database)
+                shift
+                my_node_db_name=${1}
+                ;;
+        esac
+        shift
+    done
+    echo -n "database = [${my_node_db_name}] "
+    [ -n "${my_schema_name}" ] && echo -n "schema = [${my_schema_name}]"
+    echo
 
     [ ! -d ${esg_backup_dir} ] && echo " ERROR: cannot locate backup directory [${esg_backup_dir}]" && return 1
 
@@ -5086,8 +5123,8 @@ restore_last_db_backup() {
     if [ -n "${my_schema_name}" ]; then
 	my_schema_name=_${my_schema_name}
 	backup_file=$(ls -rt | grep ${my_node_db_name}_esgf${my_schema_name}_backup_ | tail -n ${n_recent} | head -n 1)
-	echo "Restoring backup esgf schema esgf${my_schema_name} of ${my_node_db_name} <-from- ${backup_file}"
-	PGPASSWORD=${PGPASSWORD:-${pg_sys_acct_passwd}} psql -U ${postgress_user} --schema=esgf${my_schema_name} ${my_node_db_name} < ${backup_file}
+	echo "Restoring backup esgf schema esgf_${my_schema_name} of ${my_node_db_name} <-from- ${backup_file}"
+	PGPASSWORD=${PGPASSWORD:-${pg_sys_acct_passwd}} psql -U ${postgress_user} --schema=esgf_${my_schema_name} ${my_node_db_name} < ${backup_file}
 	[ $? == 0 ] && echo " [OK] " || (echo " [FAIL] " && return 1)
     else
 	backup_file=$(ls -rt | grep ${my_node_db_name}_backup_ | tail -n ${n_recent} | head -n 1)
@@ -6183,7 +6220,8 @@ usage() {
 	Database Management
 	-------------------------------
 	--config-db    - provides database only configuration to support based on note type (see --get-type)
-	--backup-db    - creates a backup of node database to file <database name <schema name>>
+	--backup-db    - creates a backup of node database to file: -db <database name> -s <schema name (suffix)>
+                         [the prefix for all schemas provided is \"esgf_\"  -s foo will reference schema esgf_foo]
 	--restore-last-db - restores from backup the last backup done <database name <schema name>>
 
 	-------------------------------
