Addressed issue with postgress asking for password instead of using the one set from questionnaire - also making sure tomcat group is present before chgrp'ing

diff --git a/esg-node b/esg-node
--- a/esg-node
+++ b/esg-node
@@ -103,7 +103,8 @@ init() {
     # Internal esgf node code versions
     #--------------------------------
     #cdat_version=${cdat_version:-"eb8b668"}
-    cdat_version=${cdat_version:-"b8bf128"}
+    #cdat_version=${cdat_version:-"b8bf128"}
+    cdat_version=${cdat_version:-"6.0.alpha"}
     esgcet_version=${esgcet_version:-"2.8.2"}
 
     #see esgf-node-manager project:
@@ -972,15 +973,15 @@ setup_postgress() {
     start_postgress
 
     #Check to see if there is a ${postgress_user} already on the system if not, make one
-    if [ -x ${postgress_install_dir}/bin/psql ] && (( $(psql -c "select count(*) from pg_roles where rolname='${postgress_user}'" postgres | tail -n +3 | head -n 1) > 0 )); then
+    if [ -x ${postgress_install_dir}/bin/psql ] && (( $(PGPASSWORD=${pg_sys_acct_passwd:=${security_admin_password}} psql -c "select count(*) from pg_roles where rolname='${postgress_user}'" postgres | tail -n +3 | head -n 1) > 0 )); then
 	echo "${postgress_user} exists!! :-)";
     else
 	echo "$postgress_install_dir/bin/createuser -U $pg_sys_acct -P -s -e $postgress_user"
 	if [ -z "${pg_sys_acct_passwd}" ]; then
-	    PGPASSWORD=${PGPASSWORD:-${pg_sys_acct_passwd}} $postgress_install_dir/bin/createuser -U $pg_sys_acct -P -s -e $postgress_user
+	    PGPASSWORD=${PGPASSWORD:-${pg_sys_acct_passwd:=${security_admin_password}}} $postgress_install_dir/bin/createuser -U $pg_sys_acct -P -s -e $postgress_user
 	    [ $? != 0 ] && echo " ERROR: Unable to create user on the system" && popd && checked_done 1
 	else
-	    PGPASSWORD=${PGPASSWORD:-${pg_sys_acct_passwd}} $postgress_install_dir/bin/createuser -U $pg_sys_acct -P -s -e $postgress_user
+	    PGPASSWORD=${PGPASSWORD:-${pg_sys_acct_passwd:-${security_admin_password}}} $postgress_install_dir/bin/createuser -U $pg_sys_acct -P -s -e $postgress_user
 	    [ $? != 0 ] && echo " ERROR: Unable to create user on the system*" && popd && checked_done 1
 	fi
     fi
@@ -4645,6 +4646,10 @@ initial_setup_questionnaire() {
 	unset input
 	((changed==1)) && echo ${security_admin_password} > ${esgf_secret_file}
 	chmod 640 ${esgf_secret_file}
+        if [ ! $(getent group ${tomcat_group}) ]; then
+	    /usr/sbin/groupadd -r ${tomcat_group}
+	    [ $? != 0 ] && [ $? != 9 ] && echo "ERROR: *Could not add tomcat system group: ${tomcat_group}" && popd && checked_done 1
+        fi
 	chown ${installer_uid}:${tomcat_group} ${esgf_secret_file}
 
 	#Use the same password when creating the postgress account
