s/fetch_esg/fetch-esgf/g

diff --git a/esg-node b/esg-node
--- a/esg-node
+++ b/esg-node
@@ -2842,7 +2842,7 @@ write_env() {
 
 #Goes to ESG distribution server and pulls down all certificates for the federation.
 #(suitable for crontabbing)
-fetch_esg_certificates() {
+fetch_esgf_certificates() {
     echo
     echo "Fetching Freshest ESG Federation Certificates..."
     #globus_global_certs_dir=/etc/grid-security/certificates
@@ -2868,7 +2868,7 @@ rebuild_truststore() {
     if [ ! -d ${globus_global_certs_dir} ] || (( force_install )) ; then
 	[ ! -d ${globus_global_certs_dir} ] && echo "Sorry, No esg certificates found... in ${globus_global_certs_dir}" || echo "(forcing fresh rebuild)"
 	echo "So fetching fresh esg certificates :-)"
-	fetch_esg_certificates
+	fetch_esgf_certificates
     fi
 
     #If you don't already have a truststore to build on....
@@ -5466,7 +5466,7 @@ usage() {
 	--generate-ssl-key-and-csr - generate new key and cert request files <key file> <cert file> [<dn>]
 				     (The 'dn' value is of the form - Ex:'/O=ESG/OU=ESG-DATA-NODE/CN=<fqdn>')
 	--install-keypair - takes as input private key and public cert files and installs them. <key> <cert> [<keystore> <alias> <password>]
-	--fetch-esg-certs - fetches and installs all current public esg federation certificates (used by globus)
+	--fetch-esgf-certs - fetches and installs all current public esgf certificates (used by globus)
 	--rebuild-truststore - converts globus' (public) ca certificates into a truststore.
 	--add-my-cert-to-truststore - adds public cert from keystore to truststore: <keystore password>
 	--clear-certs - removes the user-level public certificates' directory (used by myproxy)
@@ -5885,13 +5885,13 @@ main() {
 		    register $1 $2
 		    exit $?
 		    ;;
-		--fetch-esg-certs)
+		--fetch-esgf-certs)
 		    self_verify
 		    shift
-		    (( $# != 0 ))  && echo "error: \"--fetch-esg-certs\" must be the last argument in the arg sequence, Sorry :-(" && exit 1
+		    (( $# != 0 ))  && echo "error: \"--fetch-esgf-certs\" must be the last argument in the arg sequence, Sorry :-(" && exit 1
 		    id | grep root >& /dev/null
 		    [ $? != 0 ] && printf "[FAIL] \n\tMust be root for this option\n\n" && exit 1
-		    fetch_esg_certificates
+		    fetch_esgf_certificates
 		    exit $?
 		    ;;
 		--rebuild-truststore)
