cosmitics - untabified and formatted

diff --git a/esg-functions b/esg-functions
--- a/esg-functions
+++ b/esg-functions
@@ -5,60 +5,60 @@
 # description: Installer Functions for the ESGF Node application stack
 #
 #****************************************************************************
-#*									    *
-#*  Organization: Lawrence Livermore National Lab (LLNL)		    *
-#*   Directorate: Computation						    *
-#*    Department: Computing Applications and Research			    *
-#*	Division: S&T Global Security					    *
-#*	  Matrix: Atmospheric, Earth and Energy Division		    *
-#*	 Program: PCMDI							    *
-#*	 Project: Earth Systems Grid Fed (ESGF) Node Software Stack	    *
-#*  First Author: Gavin M. Bell (gavin@llnl.gov)			    *
-#*									    *
+#*                                                                          *
+#*  Organization: Lawrence Livermore National Lab (LLNL)                    *
+#*   Directorate: Computation                                               *
+#*    Department: Computing Applications and Research                       *
+#*      Division: S&T Global Security                                       *
+#*        Matrix: Atmospheric, Earth and Energy Division                    *
+#*       Program: PCMDI                                                     *
+#*       Project: Earth Systems Grid Fed (ESGF) Node Software Stack         *
+#*  First Author: Gavin M. Bell (gavin@llnl.gov)                            *
+#*                                                                          *
 #****************************************************************************
-#*									    *
-#*   Copyright (c) 2009, Lawrence Livermore National Security, LLC.	    *
-#*   Produced at the Lawrence Livermore National Laboratory		    *
-#*   Written by: Gavin M. Bell (gavin@llnl.gov)				    *
-#*   LLNL-CODE-420962							    *
-#*									    *
-#*   All rights reserved. This file is part of the:			    *
-#*   Earth System Grid Fed (ESGF) Node Software Stack, Version 1.0	    *
-#*									    *
-#*   For details, see http://esgf.org/					    *
-#*   Please also read this link						    *
-#*    http://esgf.org/LICENSE						    *
-#*									    *
-#*   * Redistribution and use in source and binary forms, with or	    *
-#*   without modification, are permitted provided that the following	    *
-#*   conditions are met:						    *
-#*									    *
-#*   * Redistributions of source code must retain the above copyright	    *
-#*   notice, this list of conditions and the disclaimer below.		    *
-#*									    *
+#*                                                                          *
+#*   Copyright (c) 2009, Lawrence Livermore National Security, LLC.         *
+#*   Produced at the Lawrence Livermore National Laboratory                 *
+#*   Written by: Gavin M. Bell (gavin@llnl.gov)                             *
+#*   LLNL-CODE-420962                                                       *
+#*                                                                          *
+#*   All rights reserved. This file is part of the:                         *
+#*   Earth System Grid Fed (ESGF) Node Software Stack, Version 1.0          *
+#*                                                                          *
+#*   For details, see http://esgf.org/                                      *
+#*   Please also read this link                                             *
+#*    http://esgf.org/LICENSE                                               *
+#*                                                                          *
+#*   * Redistribution and use in source and binary forms, with or           *
+#*   without modification, are permitted provided that the following        *
+#*   conditions are met:                                                    *
+#*                                                                          *
+#*   * Redistributions of source code must retain the above copyright       *
+#*   notice, this list of conditions and the disclaimer below.              *
+#*                                                                          *
 #*   * Redistributions in binary form must reproduce the above copyright    *
 #*   notice, this list of conditions and the disclaimer (as noted below)    *
-#*   in the documentation and/or other materials provided with the	    *
-#*   distribution.							    *
-#*									    *
+#*   in the documentation and/or other materials provided with the          *
+#*   distribution.                                                          *
+#*                                                                          *
 #*   Neither the name of the LLNS/LLNL nor the names of its contributors    *
-#*   may be used to endorse or promote products derived from this	    *
-#*   software without specific prior written permission.		    *
-#*									    *
+#*   may be used to endorse or promote products derived from this           *
+#*   software without specific prior written permission.                    *
+#*                                                                          *
 #*   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS    *
-#*   "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT	    *
-#*   LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS	    *
+#*   "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT      *
+#*   LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS      *
 #*   FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL LAWRENCE    *
-#*   LIVERMORE NATIONAL SECURITY, LLC, THE U.S. DEPARTMENT OF ENERGY OR	    *
-#*   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,	    *
-#*   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT	    *
-#*   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF	    *
+#*   LIVERMORE NATIONAL SECURITY, LLC, THE U.S. DEPARTMENT OF ENERGY OR     *
+#*   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,           *
+#*   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT       *
+#*   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF       *
 #*   USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND    *
-#*   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,	    *
-#*   OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT	    *
-#*   OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF	    *
-#*   SUCH DAMAGE.							    *
-#*									    *
+#*   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,     *
+#*   OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT     *
+#*   OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF     *
+#*   SUCH DAMAGE.                                                           *
+#*                                                                          *
 #****************************************************************************
 #####
 
@@ -74,13 +74,13 @@ verbose_print() { ((VERBOSE)) && echo $@; return 0; }
 debug_print() { ((DEBUG)) && echo -e $@ >&2; return 0; }
 
 _trimline() {
-	# Strips leading and trailing whitespace even if IFS is set, also
-	# removing the final newline on every line of input (i.e. the
-	# result of using this on a multi-line string will be a
-	# single-line string with no space between the last word on one
-	# line and the first word on the next, with no leading or trailing
-	# whitespace)
-	echo "$@" | perl -p -e 's/^\s+|\s+$//g';
+        # Strips leading and trailing whitespace even if IFS is set, also
+        # removing the final newline on every line of input (i.e. the
+        # result of using this on a multi-line string will be a
+        # single-line string with no space between the last word on one
+        # line and the first word on the next, with no leading or trailing
+        # whitespace)
+    echo "$@" | perl -p -e 's/^\s+|\s+$//g';
 }
 
 _version_cmp() {
@@ -170,7 +170,7 @@ _version_segment_cmp() {
 
     for index in `seq 1 $VERSIONLENGTH` ; do
         if ( [ -z ${VERSIONA[$index]##*[!0-9]*} ] ||
-             [ -z ${VERSIONB[$index]##*[!0-9]*} ] ) ; then
+                [ -z ${VERSIONB[$index]##*[!0-9]*} ] ) ; then
             # Non-numeric comparison
             if [[ ${VERSIONA[$index]} > ${VERSIONB[$index]} ]] ; then
                 echo "1"
@@ -198,15 +198,15 @@ _version_segment_cmp() {
 #-------------------------------
 checked_done() {
     if (($1)); then
-	echo ""
-	echo "Sorry..."
-	echo "This action did not complete successfully"
-	echo "Please re-run this task until successful before continuing further"
-	echo ""
-	echo "Also please review the installation FAQ it may assist you"
-	echo "http://esgf.org/wiki/ESGFNode/FAQ"
-	echo ""
-	exit 1
+        echo ""
+        echo "Sorry..."
+        echo "This action did not complete successfully"
+        echo "Please re-run this task until successful before continuing further"
+        echo ""
+        echo "Also please review the installation FAQ it may assist you"
+        echo "http://esgf.org/wiki/ESGFNode/FAQ"
+        echo ""
+        exit 1
     fi
     return 0
 }
@@ -220,15 +220,15 @@ check_version_atleast() {
     # second and 1 otherwise.
     #
     # Returns 255 if called with less than two arguments.
-
+    
     debug_print "DEBUG: check_version_atleast \$1='$1'  \$2='$2'"
-
+    
     if [[ -z "${1}" || -z "${2}" ]] ; then
         echo "CRITICAL FAILURE: check_version_atleast called with insufficient arguments" >&2
         echo "  (\$1='$1'  \$2='$2')" >&2
         return 255
     fi
-
+    
     if [ "$(_version_cmp ${1} ${2})" -ge 0 ] ; then return 0 ; fi
     return 1;
 }
@@ -246,13 +246,13 @@ check_version_between() {
     # Returns 255 if called with less than three arguments.
 
     debug_print "DEBUG: check_version_between \$1='$1'  \$2='$2'  \$3='$3'"
-
+    
     if [[ -z "${1}" || -z "${2}" || -z "${3}" ]] ; then
         echo "CRITICAL FAILURE: check_version_between called with insufficient arguments" >&2
         echo "  (\$1='$1'  \$2='$2'  \$3='$3')" >&2
         return 255
     fi
-
+    
     if [ "$(_version_cmp ${1} ${2})" -ge 0 ] \
         && [ "$(_version_cmp ${1} ${3})" -le 0 ] ; then
         return 0 ;
@@ -283,7 +283,7 @@ check_version_helper() {
 
     # Split a lone argument
     [[ $# == 1 ]] && set -- $1
-
+    
     # Spit out a nasty error message and return with 255 if there are
     # insufficient arguments (this causes the version check to fail,
     # but does NOT abort the script -- watch for the CRITICAL FAILURE
@@ -293,7 +293,7 @@ check_version_helper() {
         echo "  (\$1='$1'  \$2='$2'  \$3='$3')" >&2
         return 255
     fi   
-
+    
     if [ -z "${3}" ] ; then 
         # Only two arguments, check for a minimum version
         check_version_atleast ${1} ${2} 
@@ -470,7 +470,7 @@ check_app_version() {
     local ret=$?
     debug_print " The return value from the call to helper function check_version_ is $ret"
     [ $ret == 0 ] && return 0
-
+    
     printf "\nSorry, the detected version of ${app_dir##*/} [${current_version}] is older than required minimum version [${min_version}] \n"
     return 1
 }
@@ -479,10 +479,10 @@ check_app_version() {
 # Environment Management Utility Functions
 #----------------------------------------------------------
 remove_env() {
-	local key=${1}
-	((DEBUG)) && echo "removing ${key}'s environment from ${envfile}"
-	sed -i '/'${key}'/d' ${envfile}
-	return $?
+    local key=${1}
+    ((DEBUG)) && echo "removing ${key}'s environment from ${envfile}"
+    sed -i '/'${key}'/d' ${envfile}
+    return $?
 }
 
 remove_install_log_entry() {
@@ -555,14 +555,14 @@ pcheck() {
     local_vars=(iterations wait_time return_on_true)
     local i=0
     while [[ -n "$1" ]]; do
-	if [ "$1" == "--" ] ; then
-	    shift
-	    task_function=$1
-	    shift
-	    break
-	fi
-	eval local ${local_vars[((i++))]}=$1
-	shift
+        if [ "$1" == "--" ] ; then
+            shift
+            task_function=$1
+            shift
+            break
+        fi
+        eval local ${local_vars[((i++))]}=$1
+        shift
     done
     debug_print "iterations = ${iterations}"
     debug_print "wait_time = ${wait_time}"
@@ -572,12 +572,12 @@ pcheck() {
 
     local ret=1
     while [[ $iterations > 0 ]]; do
-	echo -n "."
-	eval ${task_function} $@
-	ret=$?
-	((return_on_true)) && [ $ret == 0 ] && break
-	((iterations != 1)) && sleep ${wait_time}
-	: $((iterations--))
+        echo -n "."
+        eval ${task_function} $@
+        ret=$?
+        ((return_on_true)) && [ $ret == 0 ] && break
+        ((iterations != 1)) && sleep ${wait_time}
+        : $((iterations--))
     done
     [ $ret == 0 ] && printf "\n${task_function} [OK]\n" || printf "\n${task_function} [FAIL]\n"
     return $ret
@@ -667,13 +667,13 @@ load_properties() {
     IFS="="
     local count=0
     while read key value; do
-	local key=$(echo $key |sed 's/\./_/g')
-	[ -z "${key}" ] && continue
-	((DEBUG)) && echo -n "loading... "
-	((DEBUG)) && echo -n "[${key}] -> "
-	((DEBUG)) && echo "[${value}]"
-	eval "${key}=\"${value}\""
-	((count++))
+        local key=$(echo $key |sed 's/\./_/g')
+        [ -z "${key}" ] && continue
+        ((DEBUG)) && echo -n "loading... "
+        ((DEBUG)) && echo -n "[${key}] -> "
+        ((DEBUG)) && echo "[${value}]"
+        eval "${key}=\"${value}\""
+        ((count++))
     done < ${property_file}
     echo "Loaded (imported) ${count} properties from ${property_file}"
     unset IFS
@@ -817,7 +817,7 @@ backup() {
     local source="$(readlink -f $1)"
     local backup_dir=${2:-${esg_backup_dir:-"/esg/backups"}}
     local num_backups_to_keep=${3:-${num_backups_to_keep:-7}}
-
+    
     echo "Backup - Creating a backup archive of ${source}"
     pushd ${source%/*} >& /dev/null
     mkdir -p ${backup_dir} >& /dev/null
@@ -825,28 +825,26 @@ backup() {
     tar czf ${backup_filename} ${source##*/}
     [ $? != 0 ] && echo " ERROR: Problem with creating backup archive: ${backup_filename}" && popd >& /dev/null && return 1
     if [ -e ${backup_filename} ]; then
-	echo "Created backup: ${backup_filename}"
+        echo "Created backup: ${backup_filename}"
     else
-	echo "Could not locate backup file ${backup_filename}"
-	popd >& /dev/null
-	return 1
+        echo "Could not locate backup file ${backup_filename}"
+        popd >& /dev/null
+        return 1
     fi
-
-
+    
+    
     #-------------
     #keep only the last num_backups_to_keep files
     pushd ${backup_dir} >& /dev/null
     local files=(`ls -t | grep ${source##*/}.\*.tgz | tail -n +$((${num_backups_to_keep}+1)) | xargs`)
     if (( ${#files[@]} > 0 )); then
-	echo "Tidying up a bit..."
-	echo "${#files[@]} old backup files to remove: ${files[@]}"
-	rm -v ${files[@]}
+        echo "Tidying up a bit..."
+        echo "${#files[@]} old backup files to remove: ${files[@]}"
+        rm -v ${files[@]}
     fi
     popd >& /dev/null
     #-------------
-
+    
     popd >& /dev/null
     return 0
-
-
 }
