Clean up...
Put git description version and check for proper git version.
Check to see that you have md5sum on your machine and alert user
accordingly.

diff --git a/esg-bootstrap b/esg-bootstrap
--- a/esg-bootstrap
+++ b/esg-bootstrap
@@ -11,6 +11,8 @@
 install_prefix=${prefix:-"/usr/local"}
 esg_dist_url=http://198.128.245.140/dist
 
+script_version="v0.0.0"
+
 id_check() {
     id | grep root >& /dev/null
     [ $? != 0 ] && printf "[FAIL] \n\tMust run this program with root's effective UID\n\n" && return 1
@@ -27,7 +29,7 @@ get_latest() {
     local fetch_file=esg-node
 
     local ret
-    echo "Checking...."
+    verbose_print "Checking...."
     checked_get ${esg_dist_url}/esgf-installer/${fetch_file} 
     ret=$?
     ((ret == 1)) && echo "ESGF Node install script (${fetch_file}) already up-to-date"
@@ -87,19 +89,23 @@ checked_get() {
     [ $? != 0 ] && echo " ERROR: Problem pulling down [${remote_file##*/}] from esg distribution site" && return 2
     diff <(md5sum ${local_file} | tr -s " " | cut -d " " -f 1) <(curl -s ${remote_file}.md5 | tr -s " " | cut -d " " -f 1) >& /dev/null
     [ $? != 0 ] && echo " WARNING: Could not verify this file!" && return 3
-    echo "[VERIFIED]"
+    verbose_print "[VERIFIED]"
     return 0
 }
 
 self_verify() {
+    md5sum /dev/null >& /dev/null
+    [ $? != 0 ] && echo "Could not find program \"md5sum\". Please find program and put it in your path and try again, Sorry :-(" && exit 1
     #echo "diff <(md5sum ${0} | tr -s " " | cut -d " " -f 1) <(curl ${esg_dist_url}/esgf-installer/${0##*/}.md5 | tr -s " " | cut -d " " -f 1) >& /dev/null "
     diff <(md5sum ${0} | tr -s " " | cut -d " " -f 1) <(curl -s ${esg_dist_url}/esgf-installer/${0##*/}.md5 | tr -s " " | cut -d " " -f 1) >& /dev/null
-    [ $? != 0 ] && echo " WARNING: Could not verify myself!" && return 3
-    echo "[VERIFIED]"
+    [ $? != 0 ] && return 3
+    verbose_print "[VERIFIED]"
     return 0
 }
 
 ############################################
+verbose_print() { ((VERBOSE)) && echo $@; return 0; }
+debug_print() { ((DEBUG)) && echo $@; return 0; }
 
 usage() {
     printf "
@@ -113,10 +119,36 @@ usage() {
 # Main
 ############################################
 
+VERBOSE=0
+DEBUG=0
+
+while [ -n "$1" ]; do 
+    case $1 in 
+	-v | --version)
+	    echo "Version: $script_version"
+	    echo "Earth Systems Grid Federation (http://esgf.org)"
+	    echo "ESGF Node Bootstrap Script"
+	    echo ""
+	    exit 0
+            ;;
+        --verbose)
+            VERBOSE=1;
+            ;;
+        --debug)
+            DEBUG=1;
+            ;;
+        *)
+            echo "unknown switch [$1]"
+            exit 1
+            ;;
+    esac
+    shift
+done
+
 if id_check 
 then
-    self_verify >& /dev/null
-    (( $? > 0 )) && printf "WARNING: $0 could not be verified!! \n(This file, ${0}, may have been tampered with or there is a newer version posted at the distribution server.\nPlease re-fetch this script.)\n\n" && exit 1
+    self_verify
+    (( $? > 0 )) && printf "WARNING: $0 could not be verified!! \n(This file, $(readlink -f ${0}), may have been tampered with or there is a newer version posted at the distribution server.\nPlease re-fetch this script.)\n\n" && exit 1
     echo "checking for updates for the ESGF Node"
     if (($# == 1)) && [ "$1" = "--help" ]; then
 	usage
