Better way of checking required filesystem layout - paving the way for rootless use

diff --git a/esg-node b/esg-node
--- a/esg-node
+++ b/esg-node
@@ -290,17 +290,20 @@ init_structure() {
     #reset esg_dist_url if necessary...
     esg_dist_url=http://198.128.245.140/dist$( ((devel == 1)) && echo "/devel" || echo "")
 
-    mkdir -p ${scripts_dir}
-    [ $? != 0 ] && echo "ERROR: could not create ${scripts_dir}... required for installation" && checked_done 1
-
-    mkdir -p ${esg_backup_dir}	&& \
-	mkdir -p ${esg_tools_dir} && \
-	mkdir -p ${esg_log_dir} && \
-	mkdir -p ${esg_config_dir} && \
-	mkdir -p ${esg_etc_dir} && \
-	mkdir -p ${tomcat_conf_dir} && \
-	touch ${config_file}
-    [ $? != 0 ] && echo "ERROR: could not create ${esg_root_dir} dir and/or subdirectories" && checked_done 1
+    #--------------
+    #Let's go down the line and make sure that we have what we need structurally on the filesystem
+    local config_check=8
+    if [ ! -e ${scripts_dir} ]; then mkdir ${scripts_dir} && ((check_config--)); else ((config_check--)); fi
+    if [ ! -e ${esg_backup_dir} ]; then mkdir ${esg_backup_dir} && ((check_config--)); else ((config_check--)); fi
+    if [ ! -e ${esg_tools_dir} ]; then mkdir ${esg_tools_dir} && ((check_config--)); else ((config_check--)); fi
+    if [ ! -e ${esg_log_dir} ]; then mkdir ${esg_log_dir} && ((check_config--)); else ((config_check--)); fi
+    if [ ! -e ${esg_config_dir} ]; then mkdir ${esg_config_dir} && ((check_config--)); else ((config_check--)); fi
+    if [ ! -e ${esg_etc_dir} ]; then mkdir ${esg_etc_dir} && ((check_config--)); else ((config_check--)); fi
+    if [ ! -e ${tomcat_conf_dir} ]; then mkdir ${tomcat_conf_dir} && ((check_config--)); else ((config_check--)); fi
+    if [ ! -e ${config_file} ]; then touch ${config_file} && ((check_config--)); else ((config_check--)); fi
+    echo ${config_check}
+    ((config_check != 0 )) && echo "ERROR: checklist incomplete [FAIL]" && checked_done 1 || echo "checklist [OK]"
+    #--------------
 
     chmod 777 ${esg_etc_dir}
 
