added --update-script option, for pulling down indicated updated install script

diff --git a/esg-node b/esg-node
--- a/esg-node
+++ b/esg-node
@@ -2566,6 +2566,35 @@ test_publication() {
     return 0
 }
 
+#NOTE: I am in the midst of refactoring some of the update/download code... it may very well be the case that I 
+# call update_script inside of setup_subsystem... it remains to be seen how much of the semantics of update I want
+# to enforce and how that informs what can be done in setup. -gavin
+
+#arg (1) - name of installation script root name. Ex:security which resolves to script file esg-security
+#arg (2) - directory on the distribution site where script is fetched from Ex: orp
+#usage: update_script security orp - looks for the script esg-security in the distriubtion directory "orp"
+update_script() {
+    local subsystem=$1
+    [ -z "${subsystem}" ] && echo "update_script [${subsystem}] requires argument!!" && checked_done 1
+    local server_dir=${2:-${subsystem}}
+    local subsystem_install_script=${scripts_dir}/esg-${subsystem}
+
+    [ ! -e "${subsystem_install_script}" ] && echo "Sorry, could not find script esg-${subsystem} to update" && return 1
+
+    pushd ${scripts_dir} >& /dev/null
+    [ $? != 0 ] && echo "ERROR: Not able to enter scripts directory" && return 2
+
+    local fetch_file=esg-${subsystem}
+    verbose_print "checked_get ./${fetch_file} ${esg_dist_url}/${server_dir}/${fetch_file} $((force_install))"
+    checked_get ./${fetch_file} ${esg_dist_url}/${server_dir}/${fetch_file} $((force_install))
+    local ret=$?
+    (( $ret > 1 )) && popd && return 1
+    chmod 755 ${fetch_file}
+
+    popd >& /dev/null
+    return 0
+}
+
 #NOTE: Here we are enforcing a bit of a convention... The name of
 #subsystem files must be in the form of esg-xxx-xxx where the script
 #contains its "main" function named setup_xxx_xxx(). The string passed
@@ -5343,6 +5372,8 @@ main() {
 		    check_prerequisites
 		    [ $? != 0 ] && echo && exit 1
 
+                    init_structure
+
 		    read_sel
 
 		#---------------
@@ -5371,10 +5402,20 @@ main() {
 		    [ $((sel & COMPUTE_BIT)) != 0 ] && setup_subsystem product-server esgf-product-server 1
 
 		#---
+		    debug_print "STARTING UPDATED SERVICES: ${sel}"
 		    start ${sel}
 
 		    exit 0
 		    ;;
+                --update-script)
+		    shift
+		    self_verify
+		    check_prerequisites
+		    [ $? != 0 ] && echo && exit 1
+                    init_structure
+                    update_script $1
+                    exit 0
+                    ;;
 		--write-env)
 		    (( (sel & WRITE_ENV_BIT) == 0 )) && ((sel+=WRITE_ENV_BIT))
 		    echo
