Check for ESGINI file's existence before attempting to sanity check anything!
Pardon Zed, Thanks for reporting this one.

Checking for esgcet (publisher) 2.10.0
DEBUG: check_module_version $1='esgcet' $2='2.10.0'
DEBUG: check_version_helper $1='2.9.0' $2='2.10.0' $3=''
DEBUG: check_version_atleast $1='2.9.0' $2='2.10.0'
The return value from the call to helper function check_version_ is 0
sed: can't read /esg/config/esgcet/esg.ini: No such file or directory
=? postgresql://esgcet:changeme@extdb.nccs.nasa.gov:5432/esgcet

 [ERROR: publisher database connection string mis-match... (see /esg/config/esgcet/esg.ini's dburl value)]

diff --git a/esg-node b/esg-node
--- a/esg-node
+++ b/esg-node
@@ -1401,13 +1401,15 @@ setup_esgcet() {
     local ret=$?
 
     #-------
-    local esgini_dburl=$(sed -n 's@[ ]*dburl[ ]*=[ ]*\(.*\)$@\1@p' ${ESGINI})
-    local db_connect_str="postgresql://${publisher_db_user}:${publisher_db_user_passwd}@$([ -n "${db_host}" ] && ([ "${db_host}" = "${esgf_host}" ] || [ "${db_host}" = "localhost" ]) && echo "localhost" || echo ${db_host}):${db_port}/${db_database}"
-    debug_print "${esgini_dburl} =? ${db_connect_str}"
-    if [ "${esgini_dburl}" != "${db_connect_str}" ]; then
-        printf "\n\n [ERROR: publisher database connection string mis-match... (see ${ESGINI}'s dburl value)] \n\n"
-        trap - INT TERM
-        exit 1
+    if [ -e "${ESGINI}" ]; then
+        local esgini_dburl=$(sed -n 's@[ ]*dburl[ ]*=[ ]*\(.*\)$@\1@p' ${ESGINI})
+        local db_connect_str="postgresql://${publisher_db_user}:${publisher_db_user_passwd}@$([ -n "${db_host}" ] && ([ "${db_host}" = "${esgf_host}" ] || [ "${db_host}" = "localhost" ]) && echo "localhost" || echo ${db_host}):${db_port}/${db_database}"
+        debug_print "${esgini_dburl} =? ${db_connect_str}"
+        if [ "${esgini_dburl}" != "${db_connect_str}" ]; then
+            printf "\n\n [ERROR: publisher database connection string mis-match... (see ${ESGINI}'s dburl value)] \n\n"
+            trap - INT TERM
+            exit 1
+        fi
     fi
     #-------
 
