expanded register accordingly since it isn't just for gateways anymore :-)
register is now applied to IDP Peers as well as the more appropriate Index Peers.
Property writing is not done in the register() call but should be done by the caller.

diff --git a/esg-node b/esg-node
--- a/esg-node
+++ b/esg-node
@@ -2131,9 +2131,11 @@ setup_tds() {
     echo "Selection: [${choice}] source: ${node_host_ip_address}   dest: ${esgf_idp_peer_name}:${esgf_idp_peer}"
 
     #----------------------
-    #Fetch and Insert the Certificate for parent gateway
+    #Fetch and Insert the Certificate of IDP Peer (which is always co-located with myproxy - at least at present)
     register ${myproxy_endpoint}
-    [ $? != 0 ] && echo " Error: could not import gateway certificate!" && checked_done 1
+    [ $? != 0 ] && echo " Error: could not import IDP Peer's certificate!" && checked_done 1
+    write_as_property myproxy_endpoint #this is used to set the registration.xml's adminPeer value (revisit this.. I should be more consistent with naming)
+    write_as_property esgf_idp_peer
     #----------------------
 
     #See thredds_content_dir set in init() - default value is ${esg_root_dir}/content
@@ -2873,7 +2875,7 @@ install_keypair() {
     [ -e "${truststore_file}" ] && mv ${truststore_file} ${truststore_file}.bak
     rebuild_truststore && add_my_cert_to_truststore ${store_password}
     [ $? != 0 ] && echo "ERROR: Problem with truststore generation" && mv ${truststore_file}.bak ${truststore_file} && exit 6
-    register
+    #register ${esgf_idp_peer}
     
     #--------------------------------------------------
     #Copy the files to where they need to go for GLOBUS 
@@ -3366,7 +3368,7 @@ export_keystore_as_globus_hostkeys() {
 #arg1 - hostname of the machine with the cert you want to get
 #(arg2 - password to truststore where cert will be inserted)
 register() {
-    echo "Installing Public Certificate of Target IDP Peer Node...( -> MyProxy endpoint: ${1:-${ESGF_IDP_PEER%%/*}})"
+    echo "Installing Public Certificate of Target Peer Node...[$1]"
     
     mkdir -p ${workdir} # >& /dev/null
     pushd ${workdir} # >& /dev/null
@@ -3379,7 +3381,7 @@ register() {
 
     pushd ${tomcat_conf_dir} >& /dev/null
     
-    local input=${1:-${ESGF_IDP_PEER%%/*}}
+    local input=${1}
     [ -z "${input}" ] && popd && echo "Could not register: No endpoint specified" && return 1
 
     local ssl_endpoint=${input%%/*} #just need the hostname
@@ -3398,8 +3400,6 @@ register() {
     
     chmod 644 ${truststore_file}
     chown ${tomcat_user}:${tomcat_group} ${truststore_file}
-
-    write_as_property myproxy_endpoint ${input}
     
     sync_with_java_truststore ${truststore_file}
 
@@ -3465,6 +3465,13 @@ set_index_peer() {
     echo
     write_as_property ${esgf_index_peer}
     #----------------------
+
+    #----------------------
+    #Fetch and Insert the Certificate for Index Peer (to let in index peer's publishingService callback)
+    register ${esgf_index_peer}
+    [ $? != 0 ] && echo " Error: could not import Index Peer's [${esgf_index_peer}] certificate!" && checked_done 1
+    #----------------------
+
 }
 
 ############################################
@@ -4779,7 +4786,7 @@ usage() {
 	${progname} --clear OR
 	${progname} --test-pub OR
 	${progname} --info OR
-	${progname} --register [gateway.host.address] ([truststore passwd])
+	${progname} --register [hostname of node] ([truststore passwd])
 	${progname} --gridftp-config [ bdm &| end-user ]
 	${progname} start OR
 	${progname} --gridftp-config [ bdm &| end-user ] start OR
