s/debug/verbose/g

diff --git a/post b/post
--- a/post
+++ b/post
@@ -63,7 +63,7 @@
 #uses: egrep, rsync (and thus ssh)
 
 devel=${devel:-0}
-debug=${debug:-0}
+verbose=${verbose:-0}
 noop=${noop:-0}
 
 while [ -n "$1" ]; do 
@@ -71,8 +71,8 @@ while [ -n "$1" ]; do
         --devel)
             devel=1
             ;;
-        --debug)
-            debug=1
+        --verbose)
+            verbose=1
             ;;
         --noop)
             noop=1
@@ -85,7 +85,7 @@ while [ -n "$1" ]; do
 done
 
 ((devel)) && echo "Pushing to development area..."
-((debug)) && echo "Debug is ON"
+((verbose)) && echo "Verbose is ON"
 ((noop)) &&  echo "Noop is ON"
 
 manifest_file=${manifest_file:-$0.manif}
@@ -112,7 +112,7 @@ while read file dest_dir; do
 
     if [ ! -e $file ]; then
 	echo -n "x"
-	((debug)) && echo " [FAIL] No Such File $file"
+	((verbose)) && echo " [FAIL] No Such File $file"
 	((++total))
 	((++fail))
 	continue
@@ -121,17 +121,17 @@ while read file dest_dir; do
     dest_dir=${dest_dir:-"${current_dir}"}
     #echo "[$file] >> [$dest_dir]"
     
-    ((debug)) && echo -n "pushing $file ---> ${esg_dist_url}/${dest_dir} " || echo -n "*"
+    ((verbose)) && echo -n "pushing $file ---> ${esg_dist_url}/${dest_dir} " || echo -n "*"
     sed 's#\(script_version=\)"\(.*\)".*$#\1"'$(git describe)'"#' ${file} > ${file}.tmp
     ((!noop))  && md5sum ${file}.tmp > ${file}.md5
     ((!noop))  && rsync -c ${file}.md5 ${esg_dist_url}/${dest_dir}/${file##*/}.md5 >& /dev/null
     echo -n "-"
     ((!noop))  && rsync -c ${file}.tmp ${esg_dist_url}/${dest_dir}/${file##*/} >& /dev/null
     if [ $? != 0 ]; then
-	((debug)) && echo "[FAIL]"
+	((verbose)) && echo "[FAIL]"
 	((++fail))
     else
-	((debug)) && echo "[OK]" 
+	((verbose)) && echo "[OK]" 
 	((++good))
     fi
     ((++total))
