Make an explicit Attribute Service check for a 'test' resource

diff --git a/globus/esg-globus b/globus/esg-globus
--- a/globus/esg-globus
+++ b/globus/esg-globus
@@ -445,6 +445,7 @@ test_globus_services() {
     debug_print "test_globus_services for ${config_type} -> [$@]"
     if [ "${config_type}" = "datanode" ]; then
         shift
+        test_auth_service
         test_gridftp_server $@
         return $?
     elif [ "${config_type}" = "gateway" ]; then
@@ -1212,8 +1213,10 @@ config_bdm_gridftp_server() {
 test_auth_service() {
     local installer_home=${installer_home:-${ESG_USER_HOME:-/usr/local/src/esgf}}
     echo -n "Testing authorization service on ${esgf_host} ... "
-    ${installer_home}/workbench/esg/extra/globus/libglobus_adq-0.9.1/libglobus_adq_client https://${esgf_host}/esg-orp/saml/soap/secure/authorizationService.htm https://${esgf_host}/esgf-idp/openid/rootAdmin gsiftp://${esgf_host}:${gridftp_server_port}//esg_dataroot/test/sftlf.nc
-    [ $? == 0 ] && echo "[OK]" || echo "[FAIL]"
+    ! ${installer_home}/workbench/esg/extra/globus/libglobus_adq-0.9.1/libglobus_adq_client https://${esgf_host}/esg-orp/saml/soap/secure/authorizationService.htm https://${esgf_host}/esgf-idp/openid/rootAdmin gsiftp://${esgf_host}:${gridftp_server_port}//esg_dataroot/test/sftlf.nc | grep -q 'NOT PERMIT' >& /dev/null
+    local ret=$?
+    [ ${ret} == 0 ] && echo "[OK]" || echo "[FAIL]"
+    return ${ret}
 }
 
 test_gridftp_server() {
