- another round of globus changes, attempting to improve the   installation/upgrade experience all around - replaces $HOME/.globus with a dot_globus var (should be   /root/.globus, never a user's home dir for the simpleCA) - merges gridftp install with all required gridftp patches (less   questions) - merges myproxy install with all requried myproxy patches (less   questions)

diff --git a/globus/esg-globus b/globus/esg-globus
--- a/globus/esg-globus
+++ b/globus/esg-globus
@@ -115,6 +115,8 @@ gsoap_version=${gsoap_version:-"2.7.15"}
 
 #-----------
 globus_location=${GLOBUS_LOCATION:-${install_prefix}/globus}
+# since script runs as root and simpleCA should be done as root, make it /root/.globus here
+dot_globus=/root/.globus
 #NOTE-RedHat/CentOS specific...
 globus_word_size=${globus_word_size:-$(file /bin/bash | perl -ple 's/^.*ELF\s*(32|64)-bit.*$/$1/g')}
 num_cpus=${num_cpus:-1}
@@ -226,6 +228,46 @@ dedup ${envfile} && source ${envfile}
 setup_globus_services() {
 
     local config_type="$1"
+    
+    echo
+    echo "*******************************"
+    echo "Setting up Globus... ($1: $config_type) - (flavor: ${globus_flavor})"
+    echo "*******************************"
+    echo
+
+    local dosetup
+    local default_val="n"
+    if [ -e ${globus_install_dir} ]; then
+        echo "Detected an existing Globus installation... at ${globus_install_dir}"
+	if [ -x ${globus_location}/bin/globus-version ]; then
+	    echo "Checking for globus ${globus_version}"
+            echo "Current globus version: $(${globus_install_dir}/bin/globus-version)"
+            check_version_atleast ${globus_location}/bin/globus-version ${globus_version}
+            [ $? == 0 ] && default_val="n" && echo "Globus version appears sufficiently current"
+	else
+	    echo "Globus installation does NOT appear to be complete.  Installation is recommended."
+	fi
+
+	if [ "${config_type}" = "datanode" ]; then
+	    if [ ! -e ${globus_location}/sbin/globus-gridftp-server ]; then
+		echo "GridFTP is not installed.  Installation is recommended";
+	    fi
+	else
+	    if [ ! -d ${dot_globus} ]; then
+		echo "The MyProxy SimpleCA is not installed.  Installation is recommended";
+	    fi
+	fi
+
+        read -p "Do you want to install/configure Globus ($1)? $([ "$default_val" = "Y" ] && echo "[Y/n]" || echo "[y/N]") " dosetup
+        [ -z "${dosetup}" ] && dosetup=$default_val
+
+        if [ "${dosetup}" != "Y" ] && [ "${dosetup}" != "y" ]; then
+            echo "Skipping Globus installation and setup - will assume Globus is setup properly"
+            return 0
+        fi
+        echo
+    fi
+
     echo "setup_globus_services for ${config_type} - ${globus_word_size}bit arch : [$*]"
     if [ "${config_type}" = "datanode" ]; then
 
@@ -235,11 +277,15 @@ setup_globus_services() {
         echo "*******************************"
         echo
 
-        echo -n "Checking for GridFTP server version ${gridftp_server_version}"
-        local g_ver="(${globus_location}/sbin/globus-gridftp-server -v 2>&1 | cut -b 24-27)"
-        check_version_with globus-gridftp-server "$g_ver" "${gridftp_server_version}"
-        local ret=$?
-        ((ret == 0)) && (( ! force_install )) && echo " [OK]" && return 0
+	if [ -x ${globus_location}/sbin/globus-gridftp-server ]; then
+            echo -n "Checking for GridFTP server version ${gridftp_server_version}"
+            local g_ver="(${globus_location}/sbin/globus-gridftp-server -v 2>&1 | cut -b 24-27)"
+            check_version_with globus-gridftp-server "$g_ver" "${gridftp_server_version}"
+            local ret=$?
+            ((ret == 0)) && (( ! force_install )) && echo " [OK]" && return 0
+	else
+	    echo "GridFTP is not installed.  Installation is recommended."
+	fi
 
         create_globus_account
         setup_globus datanode
@@ -284,14 +330,17 @@ setup_globus_services() {
         echo "*******************************"
         echo
 
-        if [ -e "/root/.globus/simpleCA" ]; then
+        if [ -d ${dot_globus}/simpleCA ]; then
             echo -n "Checking for MyProxy server version ${myproxy_version}"
             local m_ver="(${globus_location}/sbin/myproxy-server -V | cut -b 36-39)"
             check_version_with myproxy-server "$m_ver" "${myproxy_version}"
             local ret=$?
             ((ret == 0)) && (( ! force_install )) && echo " [OK]" && return 0
+	else
+	    echo "MyProxy Server is not installed.  Installation is recommended."
         fi
 
+	backup_and_remove_simpleca
         create_globus_account
         shift
         local ret=1
@@ -316,16 +365,21 @@ setup_globus_services() {
         return 1
     fi
 
-    #----------------------------------------------------------------------
-    #NOTE: this is done in upgrade_gridftp_server... but it does not "stick" after myproxy
-    # install.  to remedy this, we apply the update again here
-    globus_assist_dist_file=${globus_workdir}/${gss_assist_patch_dist_url##*/}
-    checked_get ${globus_assist_dist_file} ${gss_assist_patch_dist_url} $((force_install))
-    ${globus_location}/sbin/gpt-build -force -update ${globus_assist_dist_file} ${globus_flavor}
-    [ $? != 0 ] && echo " ERROR: unable to build from ${globus_assist_dist_file}" || echo " [OK] "
-    #----------------------------------------------------------------------
+    # install this patch after both gridftp and myproxy
+    install_gss_assist_patch
 
     return 0
+}
+
+backup_and_remove_simpleca() {
+    if [ -d ${dot_globus} ]; then
+	backup ${dot_globus}
+	rm -rf ${dot_globus}
+    fi
+    if [ -d "/etc/grid-security" ]; then
+	backup /etc/grid-security
+	rm -rf /etc/grid-security
+    fi
 }
 
 #arg1 - config_type ("datanode" ["bdm" | "end-user"] | "gateway")
@@ -399,31 +453,7 @@ setup_globus() {
         echo "You must provide a configuration type arg [datanode | gateway]"
         checked_done 1
     fi
-    
-    echo
-    echo "*******************************"
-    echo "Setting up Globus... ($1: $config_type) - (flavor: ${globus_flavor})"
-    echo "*******************************"
-    echo
 
-    local dosetup
-    local default_val="N"
-    if [ -e ${globus_install_dir} ]; then
-        echo "Detected an existing Globus installation... at ${globus_install_dir}"
-        echo "Current globus version: $(${globus_install_dir}/bin/globus-version)"
-        check_version ${globus_location}/bin/globus-version ${globus_version}
-        [ $? == 0 ] && default_val="n" && echo "Globus version is sufficiently current, upgrade not required"
-        
-        read -p "Do you want to re-install globus again from source? $([ "$default_val" = "Y" ] && echo "[Y/n]" || echo "[y/N]") " dosetup
-        [ -z "${dosetup}" ] && dosetup=$default_val
-
-        if [ "${dosetup}" != "Y" ] && [ "${dosetup}" != "y" ]; then
-            echo "Skipping Globus installation and setup - will assume Globus is setup properly"
-            return 0
-        fi
-        echo
-    fi
-    
     mkdir -p $globus_workdir
     [ $? != 0 ] && checked_done 1
     chmod a+rw $globus_workdir
@@ -475,50 +505,6 @@ setup_globus() {
 #--------------------------------------------------------------
 
 upgrade_gridftp_server() {
-    #We want to make sure the current version of globus is greater or equal to ${globus_version} (4.2.1)
-
-    echo "Checking for globus ${globus_version}"
-    check_version ${globus_location}/bin/globus-version ${globus_version}
-    [ $? == 0 ] && echo "Globus version is sufficiently current, upgrade not required"
-
-#     local performed_upgrade=0
-#     echo "Checking for gridftp-server ${gridftp_server_version}"
-#     check_version ${globus_install_dir}/sbin/globus-gridftp-server ${gridftp_server_version}
-#     if [ $? == 0 ]; then
-#         echo "Globus version is sufficiently current, upgrade not required"
-#     else
-#         echo "GridFTP - Upgrading..."
-#         pushd ${globus_workdir} >& /dev/null
-
-#         gridftp_update_dist_file=${gridftp_update_dist_url##*/}
-#         if [ ! -e ${gridftp_update_dist_file} ]; then
-#             checked_get ${gridftp_update_dist_file} ${gridftp_update_dist_url} $((force_install))
-#             (( $? > 1 )) && popd && checked_done 1
-#         fi
-#         echo "${globus_location}/sbin/gpt-build -force ${gridftp_update_dist_file} ${globus_flavor}"
-#         ${globus_location}/sbin/gpt-build -force ${gridftp_update_dist_file} ${globus_flavor}
-#         [ $? != 0 ] && echo " ERROR: unable to build from ${gridftp_update_dist_file}" || (echo " [OK] " && ((performed_upgrade=1)) )
-#     fi
-
-    #Only jump to asking the user about installing patches if it is
-    #determined that there is already an up-to-date gridftp install
-    #i.e. no upgrade has been performed. (performed_upgrade == 0) If
-    #an upgrade had to be performed, don't even ask and apply the
-    #patches.  However, we want to set the default to the question as
-    #"N" to make it easier to breeze through.
-
-    local install_patches
-    local default_val="N"
-    if((performed_upgrade==0)); then
-        read -p "Would you like to install necessary GridFTP patches to current install? $([ "$default_val" = "N" ] && echo "[y/N]" || echo "[Y/n]") " install_patches
-        [ -z "${install_patches}" ] && install_patches=$default_val
-
-        if [ "${install_patches}" != "Y" ] && [ "${install_patches}" != "y" ]; then
-            echo "Skipping Gridftp patch installation - will assume Globus is patched properly"
-            return 0
-        fi
-        echo
-    fi
 
     #-------
     echo "Installing custom gsi authz interface patch..."
@@ -531,8 +517,13 @@ upgrade_gridftp_server() {
     make && make install
     [ $? != 0 ] && (echo " ERROR: unable to build from ${gridftp_update_dist_file}" && popd && popd && checked_done 1) || echo " [OK] "
     popd >& /dev/null
+    checked_done 0
     #-------
+}
 
+install_gss_assist_patch() {
+
+    #-------
     echo "Installing gss assist patch..."
     gss_assist_patch_dist_file=${gss_assist_patch_dist_url##*/}
     if [ ! -e ${gss_assist_patch_dist_file} ]; then
@@ -550,6 +541,7 @@ upgrade_gridftp_server() {
     ${globus_location}/sbin/globus-gridftp-server -v
     popd >& /dev/null
     checked_done 0
+    #-------
 }
 
 
@@ -957,24 +949,24 @@ config_gridftp_server() {
 
     local dosetup
     local default_val="Y"
-    if [ -x ${globus_install_dir}/sbin/globus-gridftp-server ]; then
-        echo "Detected an existing Globus GridFTP Server installation..."
+#    if [ -x ${globus_install_dir}/sbin/globus-gridftp-server ]; then
+#        echo "Detected an existing Globus GridFTP Server installation..."
         
         write_as_property gridftp_server_port
 
-        check_version ${globus_install_dir}/sbin/globus-gridftp-server ${gridftp_server_version}
-        [ $? == 0 ] && default_val="n" && echo "GridFTP version is sufficiently current, upgrade not required"
+#        check_version ${globus_install_dir}/sbin/globus-gridftp-server ${gridftp_server_version}
+#        [ $? == 0 ] && default_val="n" && echo "GridFTP version is sufficiently current, upgrade not required"
+#
+#        read -p "Do you want to continue with GridFTP ESG Configuration? $([ "$default_val" = "Y" ] && echo "[Y/n]" || echo "[y/N]") " dosetup
+#        [ -z "${dosetup}" ] && dosetup=$default_val
 
-        read -p "Do you want to continue with GridFTP ESG Configuration? $([ "$default_val" = "Y" ] && echo "[Y/n]" || echo "[y/N]") " dosetup
-        [ -z "${dosetup}" ] && dosetup=$default_val
+#        if [ "${dosetup}" != "Y" ] && [ "${dosetup}" != "y" ] ; then 
+#            echo "Skipping Globus installation and setup - will assume Globus is setup properly"
+#            return 0
+#        fi
+#        echo
+#    fi
 
-        if [ "${dosetup}" != "Y" ] && [ "${dosetup}" != "y" ] ; then 
-            echo "Skipping Globus installation and setup - will assume Globus is setup properly"
-            return 0
-        fi
-        echo
-    fi
-    
     #TODO: Decide how to maintain semantic integrity
     [ -z ${globus_sys_acct} ] && echo " ERROR: globus_sys_acct=[${globus_sys_acct}] must be set" && checked_done 1
     
@@ -1085,31 +1077,31 @@ config_bdm_gridftp_server() {
     echo "GridFTP - Configuration... for Bulk Data Mover (BDM)"
     echo
     echo "*******************************"
-    echo "Setting up GridFTP... (BDM Amenable Configureation)"
+    echo "Setting up GridFTP... (BDM Configuration)"
     echo "*******************************"
     echo
 
     local dosetup
     local default_val="Y"
-    if [ -x ${globus_install_dir}/sbin/globus-gridftp-server ]; then
-        echo "Detected an existing Globus BDM GridFTP Server installation..."
-        echo "$(${globus_install_dir}/sbin/globus-gridftp-server --version)"
+#    if [ -x ${globus_install_dir}/sbin/globus-gridftp-server ]; then
+#        echo "Detected an existing Globus BDM GridFTP Server installation..."
+#        echo "$(${globus_install_dir}/sbin/globus-gridftp-server --version)"
 
         write_as_property gridftp_bdm_server_port
 
-        check_version ${globus_install_dir}/sbin/globus-gridftp-server ${gridftp_server_version}
-        [ $? == 0 ] && default_val="n" && echo "GridFTP version is sufficiently current, upgrade not required"
-        
-        read -p "Do you want to continue with BDM GridFTP ESG Configuration? $([ "$default_val" = "Y" ] && echo "[Y/n]" || echo "[y/N]") " dosetup
-        [ -z "${dosetup}" ] && dosetup=$default_val
-        
-        if [ "${dosetup}" != "Y" ] && [ "${dosetup}" != "y" ] ; then 
-            echo "Skipping Globus installation and setup - will assume Globus is setup properly"
-            return 0
-        fi
-        echo
-    fi
-    
+#        check_version ${globus_install_dir}/sbin/globus-gridftp-server ${gridftp_server_version}
+#        [ $? == 0 ] && default_val="n" && echo "GridFTP version is sufficiently current, upgrade not required"
+#        
+#        read -p "Do you want to continue with BDM GridFTP ESG Configuration? $([ "$default_val" = "Y" ] && echo "[Y/n]" || echo "[y/N]") " dosetup
+#        [ -z "${dosetup}" ] && dosetup=$default_val
+#        
+#        if [ "${dosetup}" != "Y" ] && [ "${dosetup}" != "y" ] ; then 
+#            echo "Skipping Globus installation and setup - will assume Globus is setup properly"
+#            return 0
+#        fi
+#        echo
+#    fi
+
     #TODO: Decide how to maintain semantic integrity
     [ -z ${globus_sys_acct} ] && echo " ERROR: globus_sys_acct=[${globus_sys_acct}] must be set" && checked_done 1
     
@@ -1145,6 +1137,8 @@ config_bdm_gridftp_server() {
     fi
 
     pushd ${gridftp_bdm_dist_dir}/source >& /dev/null
+    lastdir=`pwd`
+    cd ${gridftp_bdm_dist_dir}/source
     ./bootstrap 
     [ $? != 0 ] && echo " ERROR: could not perform bootstrap" && checked_done 1
 
@@ -1158,6 +1152,7 @@ config_bdm_gridftp_server() {
     else
         echo " ERROR: Could NOT successfully build GRIDFTP!"
         popd >& /dev/null
+	cd ${lastdir}
         checked_done 1
     fi
 
@@ -1184,6 +1179,7 @@ config_bdm_gridftp_server() {
     chgrp -R ${globus_sys_acct_group} ${globus_location}
 
     popd >& /dev/null
+    cd ${lastdir}
     checked_done 0
     write_as_property gridftp.service.type "Replication"
 }
@@ -1448,21 +1444,21 @@ config_myproxy_server() {
     #------------------------------------
 
     #You have decided to do an install but an installation is already detected
-    if ((install_mode)) && [ -e ${globus_location}/sbin/myproxy-server ]; then
-        local answer="Y"
-        echo "NOTICE:"
-        echo "   Detected that the myproxy-server is already present!"
-        read -p "   Do you still wish to INSTALL myproxy (and usurp what is present)? [y/N] " answer
-        [ -z "${answer}" ] && answer="N"
-        if [ "${answer}" = "Y" ] || [ "${answer}" = "y" ]; then
-            install_mode=1
-            echo "(${answer})"
-        else
-            install_mode=0
-            echo "(n)"
-        fi
-        unset answer
-    fi
+#    if ((install_mode)) && [ -e ${globus_location}/sbin/myproxy-server ]; then
+#        local answer="Y"
+#        echo "NOTICE:"
+#        echo "   Detected that the myproxy-server is already present!"
+#        read -p "   Do you still wish to INSTALL myproxy (and usurp what is present)? [y/N] " answer
+#        [ -z "${answer}" ] && answer="N"
+#        if [ "${answer}" = "Y" ] || [ "${answer}" = "y" ]; then
+#            install_mode=1
+#            echo "(${answer})"
+#        else
+#            install_mode=0
+#            echo "(n)"
+#        fi
+#        unset answer
+#    fi
 
     #You have selected to do an update but the program is not even installed in the first place!
     if ((!install_mode)) && [ ! -e ${globus_location}/sbin/myproxy-server ]; then
@@ -1523,7 +1519,7 @@ config_myproxy_server() {
         # local grab
         
         [ -d /tmp/root_tmp_ca_setup ] && tar cvzf /tmp/root_tmp_ca_setup.$(date ${date_format}).tgz /tmp/root_tmp_ca_setup && rm -rf /tmp/root_tmp_ca_setup
-        #[ -d ${HOME}/.globus/simpleCA ] && read -p "Would you like to remove the current CA setup? [Y/n] " && rm -rf ${HOME}/.globus/simpleCA
+        #[ -d ${dot_globus}/simpleCA ] && read -p "Would you like to remove the current CA setup? [Y/n] " && rm -rf ${dot_globus}/simpleCA
         ${globus_location}/setup/globus/setup-simple-ca | tee /tmp/globus_simpleca.log #> output
         [ $? != 0 ] && echo "May have to remove offending dir" && popd && return 1
         
@@ -1596,9 +1592,9 @@ config_myproxy_server() {
         echo "command: ${globus_location}/setup/globus_simple_ca_${ca_hash}_setup/setup-gsi -default"
         
         #move the old files outta the way!
-        [ -e ~/.globus/host/hostcert_request.pem ] && cp -v  ~/.globus/host/hostcert_request.pem ~/.globus/host/hostcert_request.pem.$(date ${date_format}).bak
-        [ -e ~/.globus/host/hostcert.pem ] && cp -v  ~/.globus/host/hostcert.pem ~/.globus/host/hostcert.pem.$(date ${date_format}).bak
-        [ -e ~/.globus/host/hostkey.pem ] && cp -v  ~/.globus/host/hostkey.pem ~/.globus/host/hostkey.pem.$(date ${date_format}).bak
+        [ -e ${dot_globus}/host/hostcert_request.pem ] && cp -v ${dot_globus}/host/hostcert_request.pem ${dot_globus}/host/hostcert_request.pem.$(date ${date_format}).bak
+        [ -e ${dot_globus}/host/hostcert.pem ] && cp -v ${dot_globus}/host/hostcert.pem ${dot_globus}/host/hostcert.pem.$(date ${date_format}).bak
+        [ -e ${dot_globus}/host/hostkey.pem ] && cp -v ${dot_globus}/host/hostkey.pem ${dot_globus}/host/hostkey.pem.$(date ${date_format}).bak
         
         ${globus_location}/setup/globus_simple_ca_${ca_hash}_setup/setup-gsi -default
         
@@ -1623,7 +1619,7 @@ config_myproxy_server() {
         echo "Do not regognize directive... return 1"
     fi
 
-    local simpleCA_cert=${HOME}/.globus/simpleCA/cacert.pem
+    local simpleCA_cert=${dot_globus}/simpleCA/cacert.pem
     if [ -e "${simpleCA_cert}" ]; then
         cp -v ${simpleCA_cert} /etc/grid-security/certificates/ && echo -n "." || echo -n "x"
 	chown -R ${installer_uid}:${installer_gid} /etc/grid-security/certificates/${simpleCA_cert##/*/} >& /dev/null && echo -n "." || echo -n "x"
@@ -1641,15 +1637,15 @@ config_myproxy_server() {
     [ $((install_mode)) == 0 ] && return 0
 
     #allow for fetched keys to be written in this location.
-    echo "chown -R ${installer_uid}:${installer_gid} $HOME/.globus"
-    chown -R ${installer_uid}:${installer_gid} $HOME/.globus 
+    echo "chown -R ${installer_uid}:${installer_gid} ${dot_globus}"
+    chown -R ${installer_uid}:${installer_gid} ${dot_globus} 
     [ $? != 0 ] && echo "**WARNING**: Could not change owner successfully - this will lead to inability to use myproxy and publisher properly!"
     
     #NOTE: for more info on keys and troubleshooting see:
     #http://www.ci.uchicago.edu/wiki/bin/view/ESGProject/MyProxyCertificateReplacementTesting
 
     #NOTE: To test that the simple CA's key's password is what you think it is:
-    #openssl rsa -in ~/.globus/simpleCA/private/cakey.pem -text -noout
+    #openssl rsa -in ${dot_globus}/simpleCA/private/cakey.pem -text -noout
 
 
     #--------------------
