generation of globus key and csr + w/ small node type guard on _relocate_n_relink function

diff --git a/globus/esg-globus b/globus/esg-globus
--- a/globus/esg-globus
+++ b/globus/esg-globus
@@ -1476,13 +1476,13 @@ generate_globus_key_and_csr() {
     echo "Generating (globus) private host key... "
     local gendir=${1:-gen-self-cert}
     mkdir -p ${gendir}
-    rm -v -rf ${gendir}/hostkey*.pem
-    rm -v -rf ${gendir}/hostcert*.pem
+    rm -rf ${gendir}/hostkey*.pem
+    rm -rf ${gendir}/hostcert*.pem
 
     #-----------------------------------------------------------------
     echo "Generating (globus) Certificate Signing Request (csr)... "
     debug_print "$GLOBUS_LOCATION/bin/grid-cert-request -host `hostname --fqdn` -dir ${gendir} -force"
-    $GLOBUS_LOCATION/bin/grid-cert-request -host `hostname --fqdn` -dir ${gendir} -force
+    $GLOBUS_LOCATION/bin/grid-cert-request -host `hostname --fqdn` -dir ${gendir} -force &> /dev/null
     #-----------------------------------------------------------------
     [ $? != 0 ] && echo "oops" && return 1
 
@@ -1494,7 +1494,16 @@ generate_globus_key_and_csr() {
     chmod 600 /etc/grid-security/hostkey.pem
     chmod 644 /etc/grid-security/${esgf_host:-$(hostname --fqdn)}-esg-node-globus.csr
 
-    echo "Globus CSR Generated [/etc/grid-security/${esgf_host:-$(hostname --fqdn)}-esg-node-globus.csr] [OK] "
+    echo -n "Globus CSR Generated [/etc/grid-security/${esgf_host:-$(hostname --fqdn)}-esg-node-globus.csr] "
+
+    #NOTES: This is how you check that certs belong to eachother... the resulting values must all be the same
+    #openssl req  -noout -modulus -in esgf-node3.llnl.gov-esg-node-globus.csr | openssl md5
+    #openssl rsa  -noout -modulus -in hostkey.pem  | openssl md5
+    #openssl x509 -noout -modulus -in hostcert.pem | openssl md5
+
+    local pair_hash=($((openssl req -noout -modulus -in /etc/grid-security/${esgf_host:-$(hostname --fqdn)}-esg-node-globus.csr | openssl md5 ; openssl rsa -noout -modulus -in /etc/grid-security/hostkey.pem | openssl md5) | uniq))
+    (( 1 == ${#pair_hash[@]} )) && printf "[OK] (${pair_hash})\n\n" && printf "Please email the generated csr to esgf-ca@lists.llnl.gov, Thank you\n\n" || (printf "[FAIL]\n\n" && return 1)
+
     return 0
 }
 
