Spark test now passes with Mesos on single-instance Zookeeper

diff --git a/compute-tools/esg-compute-tools b/compute-tools/esg-compute-tools
--- a/compute-tools/esg-compute-tools
+++ b/compute-tools/esg-compute-tools
@@ -247,14 +247,20 @@ test_mesos() {
     local standaloneMesosMasterURL=$(get_config_ip eth0):5050
     run_mesos_start_slave $standaloneMesosMasterURL
     echo "Testing Spark on Mesos..."
-    ${spark_install_dir}/run spark.examples.SparkPi $standaloneMesosMasterURL >& /dev/null && sparkOnMesosStandalone=$? && run_mesos_stop_cluster
+    ${spark_install_dir}/run spark.examples.SparkPi $standaloneMesosMasterURL && local sparkOnMesosStandalone=$? && run_mesos_stop_cluster
     echo -n "Tested Mesos (non-fault-tolerant) with Spark...   "
     [ $sparkOnMesosStandalone == 0 ] && echo "[ PASSED ]" || echo "[ FAILED ]"
 
-    #stop_mesos_zookeeper
-    #start_mesos_zookeeper
-    
-    # TODO Yuck hard-coding
+    echo
+    echo "Test 2: Mesos with Spark Framework, Fault Tolerance via Single Zookeeper Instance"
+    start_zookeeper_server ${zookeeper_confdir}/zoo_standalone.cfg
+    run_mesos_start_master --port=5050 --zk=zk://localhost:2181/znode
+    run_mesos_start_slave zk://localhost:2181/znode
+    echo "Testing Spark on Mesos with Single Zookeeper Instance for fault tolerance..."
+    ${spark_install_dir}/run spark.examples.SparkPi zk://localhost:2181/znode && local sparkOnMesosSingleZookeeper=$? && run_mesos_stop_cluster && stop_zookeeper_server ${zookeeper_confdir}/zoo_standalone.cfg
+    echo -n "Tested Mesos + Spark on Standalone Zookeeper instance..."
+    [ $sparkOnMesosSingleZookeeper == 0 ] && echo "[ PASSED ]" || echo "[ FAILED ]"
+
     #local zkflag_spark=zk://localhost:2181,localhost:2182,localhost:2183,localhost:2184,localhost:2185/znode 
     #local sparkResult=$(${spark_install_dir}/run spark.examples.SparkPi $zkflag_spark) # >& /dev/null && echo $?)   
     #echo -n "Tested Mesos Local Cluster with Spark...   "
