Clojure now installs and unpacks correctly into install prefix.

diff --git a/compute-tools/esg-compute-languages b/compute-tools/esg-compute-languages
--- a/compute-tools/esg-compute-languages
+++ b/compute-tools/esg-compute-languages
@@ -80,7 +80,7 @@ install_prefix=${install_prefix:-"/usr/local"}
 DEBUG=${DEBUG:-0}
 java_placeholder="$install_prefix/java"
 java_install_path_config_param="--with-java-home=$java_placeholder/bin/java"
-compress_extensions=".tar.gz|.tar.bz2|.tgz|.bz2|.tar"
+compress_extensions=".tar.gz|.tar.bz2|.tgz|.bz2|.tar|.zip"
 
 #--------------------------------
 # External programs' versions
@@ -112,6 +112,25 @@ uninstall_clojure () {
 get_clojure () {
 	# Debug Placeholder
 	uninstall_clojure
+
+    # Retrieve Clojure Distribution File
+	local clojure_dist_file=${clojure_dist_url##*/}
+	local clojure_dist_dir=$(echo ${clojure_dist_file} | awk 'gsub(/('$compress_extensions')/,"")')
+
+	if [ ! -e ${clojure_install_dir} ]; then
+		echo "Don't see Clojure distribution directory ${clojure_install_dir}"
+		wget -O "${install_prefix}/${clojure_dist_file}" ${clojure_dist_url}
+		#[ $? != 0 ] && echo " ERROR: Could not download Clojure: ${clojure_dist_file}" && popd && checked_done 1
+		echo "Unpacking ${clojure_dist_file}..."
+		unzip -q "${install_prefix}/${clojure_dist_file}" -d ${install_prefix}
+		mv "${install_prefix}/${clojure_dist_dir}" ${clojure_install_dir}
+		#[ $? != 0 ] && echo " ERROR: Could not extract Clojure: ${clojure_dist_file}" && popd && checked_done 1
+	fi
+	
+	# Remove Clojure Distribution File
+	if [ -e "${install_prefix}/${clojure_dist_file}" ]; then
+        rm "${install_prefix}/${clojure_dist_file}"
+	fi
 }
 
 compute_setup_clojure () {
