Mesos now tested with Spark; works fine except some weird stderr outputs.

diff --git a/compute-tools/esg-compute-tools b/compute-tools/esg-compute-tools
--- a/compute-tools/esg-compute-tools
+++ b/compute-tools/esg-compute-tools
@@ -115,7 +115,7 @@ hadoop_max_version=${hadoop_max_version:="1.0.4"}
 #--------------------------------
 mesos_install_dir=${MESOS_HOME:-${install_prefix}/mesos}
 mesos_git_url="git://git.apache.org/mesos.git"
-mesos_build_dir=${MESOS_BUILD_HOME:-${install_prefx}/mesos} # TODO /mesos/build...
+mesos_build_dir=${MESOS_BUILD_HOME:-${install_prefix}/mesos} # TODO /mesos/build...
 spark_install_dir=${SPARK_HOME:-${install_prefix}/spark}
 spark_git_url="git://github.com/mesos/spark.git"
 zookeeper_install_dir=${ZOOKEEPER_HOME:-${install_prefix}/zookeeper}
@@ -208,25 +208,42 @@ config_mesos() {
 	#
 	# [TODO] Zookeeper URL Configuration for Mesos master running
 	#   Required for fault tolerance mode
-
-	echo	
+	echo
 }
 
 test_mesos() {
-	# At this time, Mesos and Zookeeper have some incompatibilities for the testing mechanism.
-	# This Mesos Test ensures that Spark and Hadoop can run locally on Mesos. 
-	# Future TODO: Language-specific test frameworks
-
-	# Test the installation of Mesos
+	# Currently running Mesos + Zookeeper with custom deploy methods, tested here.
+	# Test 1: Mesos + Spark
+	# Test 2: Mesos + Hadoop
+	# Test 3: Mesos + Hadoop + Spark
+	# TODO Add Zookeeper functionality
+	
 	echo
-    echo "Testing Mesos configuration... "
+	echo "Test 1: Mesos with Spark Framework, [TODO Zookeeper Quorum Management]"
+	# TODO Starts Zookeeper
+	run_mesos_start_master && run_mesos_start_slave
+	local mesos_master_url=$(get_config_ip eth0) # Move me to a method TODO
+	local sparkResult=$(${spark_install_dir}/run spark.examples.SparkPi "$mesos_master_url:5050" >& /dev/null && echo $?) 	
+	echo -n "Tested Mesos Local Cluster with Spark...   "
+	[ $sparkResult == 0 ] && echo "[ PASSED ]" || echo "[ FAILED ]"
+	run_mesos_stop_slave && run_mesos_stop_master
+	# TODO Clear termination output?
 
+	echo "Test 2: Mesos with Hadoop Framework, [TODO Zookeeper Quorum Management]"
+	# Starts Zookeeper, starts Mesos, runs Hadoop pseudo-distributed test job on Mesos
+	echo -n "Tested Mesos Local Cluster with Spark...   "
+	echo "[ TBD ]"
+
+	echo "Test 3: Mesos with Hadoop, Spark, and [TODO Zookeeper Quorum Management]"
+	# Starts Zookeeper, starts Mesos, runs Spark job and Hadoop job on mesos
+	echo -n "Tested Mesos Local Cluster with Spark...   "
+	echo "[ TBD ]"
 
 }
 
 run_mesos_start_master() {
 	# TODO Start with Zookeeper URL, ESGF IP address
-	${mesos_build_dir}/bin/mesos-master.sh	
+	${mesos_build_dir}/bin/mesos-master.sh --quiet &	
 }
 
 run_mesos_stop_master() {
@@ -240,8 +257,8 @@ run_mesos_stop_slave() {
 run_mesos_start_slave() {
 	# TODO Run with ESGF Ip address for mesos master url
 	# TODO figure out correct memory resources
-	local $mesos_master_url=$(get_config_ip eth0)
-	${mesos_build_dir}/bin/mesos-slave.sh "--master=$mesos_master_url:5050" "\"--resources=cpus:2;mem:1024\""
+	local mesos_master_url=$(get_config_ip eth0)
+	${mesos_build_dir}/bin/mesos-slave.sh --quiet "--master=$mesos_master_url:5050" "--resources=cpus:2;mem:1024" &
 }
 
 clean_mesos() {
