Zookeeper now runs on Mesos in Replication Mode, but tests/code clean-up in progress.

diff --git a/compute-tools/esg-compute-tools b/compute-tools/esg-compute-tools
--- a/compute-tools/esg-compute-tools
+++ b/compute-tools/esg-compute-tools
@@ -241,17 +241,21 @@ test_mesos() {
     # Test 1: Mesos + Spark
     # Test 2: Mesos + Hadoop
     # Test 3: Mesos + Hadoop + Spark
-    # TODO Add Zookeeper functionality
     
     echo
     echo "Test 1: Mesos with Spark Framework, [TODO Zookeeper Quorum Management]"
-    # TODO Starts Zookeeper
-    run_mesos_start_master && run_mesos_start_slave && run_mesos_start_slave
-    local mesos_master_url=$(get_config_ip eth0) # Move me to a method TODO
-    local sparkResult=$(${spark_install_dir}/run spark.examples.SparkPi "$mesos_master_url:5050" >& /dev/null && echo $?)   
-    echo -n "Tested Mesos Local Cluster with Spark...   "
-    [ $sparkResult == 0 ] && echo "[ PASSED ]" || echo "[ FAILED ]"
     run_mesos_stop_cluster
+    stop_mesos_zookeeper
+    start_mesos_zookeeper
+    
+    # TODO Yuck hard-coding
+    #local zkflag_spark=zk://localhost:2181,localhost:2182,localhost:2183,localhost:2184,localhost:2185/znode 
+    #local sparkResult=$(${spark_install_dir}/run spark.examples.SparkPi $zkflag_spark) # >& /dev/null && echo $?)   
+    #echo -n "Tested Mesos Local Cluster with Spark...   "
+    #[ $sparkResult == 0 ] && echo "[ PASSED ]" || echo "[ FAILED ]"
+    
+    run_mesos_stop_cluster
+    stop_mesos_zookeeper
 
     echo
     echo "Test 2: Mesos with Hadoop Framework, [TODO Zookeeper Quorum Management]"
@@ -268,28 +272,75 @@ test_mesos() {
 
 }
 
-run_mesos_start_master() {
-    # TODO Start with Zookeeper URL, ESGF IP address
-    ${mesos_build_dir}/bin/mesos-master.sh --quiet &    
+start_mesos_zookeeper() {
+    # Start Zookeeper Locally replicated server
+    local quorum=5
+    for (( n=1; n <= $quorum; n++ ))
+    do
+        start_zookeeper_server ${zookeeper_confdir}/zoo_local_replicated_$n.cfg
+    done 
+
+    # Start Mesos Master on locally replicated server+port
+    local zkport=2181
+    local mesosport=5050
+    for (( p=1; p <= $quorum; p++ ))
+    do
+        # TODO This should be written to a file in Zookeeper's configuration...
+        local flag="--zk=zk://localhost:2181,localhost:2182,localhost:2183,localhost:2184,localhost:2185/znode --port=$((mesosport++))"
+        run_mesos_start_master $flag
+    done
+
+    # Start Zookeeper Slaves
+    
 }
 
-run_mesos_stop_cluster() {
-    # Stop Master without parent shell termination notification
-    master_pid=$(pgrep mesos-master)
-    kill $master_pid
-    wait $master_pid 2>/dev/null
+stop_mesos_zookeeper() {
+    local quorum=5
+    for (( n=1; n <= $quorum; n++ ))
+    do
+        stop_zookeeper_server ${zookeeper_confdir}/zoo_local_replicated_$n.cfg 
+    done
+    stop_zookeeper_server ${zookeeper_confdir}/zoo_standalone.cfg
+}
 
-    # Stop Slaves
-    slave_pid=$(pgrep mesos-slave)
-    kill $slave_pid
-    wait $slave_pid 2>/dev/null
+run_mesos_start_master() {
+    # Takes as input any flags (besides quiet) to pass to the master
+    # TODO Start with Zookeeper URL, ESGF IP address
+    echo "Starting Mesos Master"
+    ${mesos_build_dir}/bin/mesos-master.sh --quiet $@ &
+    [ $? == 0 ] && echo "[ Mesos Master now running ]" || echo "[Mesos Master failed to run]"  
 }
 
 run_mesos_start_slave() {
     # TODO Run with ESGF Ip address for mesos master url
     # TODO figure out correct memory resources
+    echo "Starting Mesos Slave"
     local mesos_master_url=$(get_config_ip eth0)
-    ${mesos_build_dir}/bin/mesos-slave.sh --quiet "--master=$mesos_master_url:5050" "--resources=cpus:2;mem:1024" &
+    ${mesos_build_dir}/bin/mesos-slave.sh "--master=$1" "--resources=cpus:2;mem:1024" &
+}
+
+run_mesos_stop_cluster() {
+    # Stop Master without parent shell termination notification
+    master_pid=$(pgrep mesos-master)
+    if [ $? == 0 ]; then
+        echo -n "Stopping Mesos Master ..."
+        kill $master_pid
+        wait $master_pid 2>/dev/null
+        echo "STOPPED"
+    else
+        echo "Mesos master not currently running"
+    fi
+
+    # Stop Slaves
+    slave_pid=$(pgrep mesos-slave)
+    if [ $? == 0 ]; then
+        echo -n "Stopping Mesos Slaves ..."
+        kill $slave_pid
+        wait $slave_pid 2>/dev/null
+        echo "STOPPED"
+    else
+        echo "Mesos slaves not currently running"
+    fi
 }
 
 clean_mesos() {
@@ -832,8 +883,9 @@ test_zookeeper() {
 
 start_zookeeper_server() {
     # Starts Zookeeper server with a given configuration file
+    echo "[ Starting Zookeeper... ]"
     ${zookeeper_install_dir}/bin/zkServer.sh start $1 >& /dev/null
-    # TODO Check here for any issues with starting server
+    [ $? == 0 ] && echo "[ Zookeeper running from configuration: $1 ]" || echo "[Zookeeper failed to run, see configuration: $1 ]"
 }
 
 stop_zookeeper_server() {
