Mesos runs on Zookeeper Standalone now, reads cluster config from file.

diff --git a/compute-tools/esg-compute-tools b/compute-tools/esg-compute-tools
--- a/compute-tools/esg-compute-tools
+++ b/compute-tools/esg-compute-tools
@@ -130,6 +130,8 @@ hadoop_work_dir=${hadoop_work_dir:-${install_prefix}/hadoop_working}
 zookeeper_client_port=2181
 zookeeper_workdir=${zookeeper_install_dir}/zookeeper_working
 zookeeper_confdir=${zookeeper_install_dir}/conf
+zookeeper_replicated_master_url_file=${zookeeper_confdir}/zoo_url_local_replicated.cfg
+zookeeper_standalone_master_url_file=${zookeeper_confdir}/zoo_url_standalone.cfg
 
 #-------------------------------
 # Internal script variables
@@ -242,7 +244,8 @@ test_mesos() {
     # Currently running Mesos + Zookeeper with custom deploy methods, tested here.
     # Test 1: Mesos + Spark, Standalone 
     # Test 2: Mesos + Spark with Quorum Management
-     
+   
+    #$zookeeper_replicated_master_url_file     
     echo
     echo "${bold_text}Test 1: Mesos with Spark Framework, Standalone (Fault-Tolerance Mode Disabled)${normal_text}"
     run_mesos_start_master --port=5050
@@ -250,18 +253,18 @@ test_mesos() {
     run_mesos_start_slave $standaloneMesosMasterURL
     echo "Testing Spark on Mesos..."
     ${spark_install_dir}/run spark.examples.SparkPi $standaloneMesosMasterURL && local sparkOnMesosStandalone=$? && run_mesos_stop_cluster
-    echo -n "Tested Mesos (non-fault-tolerant) with Spark...   "
-    [ $sparkOnMesosStandalone == 0 ] && echo "[ PASSED ]" || echo "[ FAILED ]"
+    echo -n "${bold_text}Tested Mesos (non-fault-tolerant) with Spark...   ${normal_text}"
+    [ $sparkOnMesosStandalone == 0 ] && echo "${bold_text}[ PASSED ]${normal_text}" || echo "${bold_text}[ FAILED ]${normal_text}"
 
     echo
     echo "${bold_text}Test 2: Mesos with Spark Framework, Fault Tolerance via Single Zookeeper Instance${normal_text}"
     start_zookeeper_server ${zookeeper_confdir}/zoo_standalone.cfg
-    run_mesos_start_master --port=5050 --zk=zk://localhost:2181/znode
-    run_mesos_start_slave zk://localhost:2181/znode
-    echo "Testing Spark on Mesos with Single Zookeeper Instance for fault tolerance..."
-    ${spark_install_dir}/run spark.examples.SparkPi zk://localhost:2181/znode && local sparkOnMesosSingleZookeeper=$? && run_mesos_stop_cluster && stop_zookeeper_server ${zookeeper_confdir}/zoo_standalone.cfg
-    echo -n "Tested Mesos + Spark on Standalone Zookeeper instance..."
-    [ $sparkOnMesosSingleZookeeper == 0 ] && echo "[ PASSED ]" || echo "[ FAILED ]"
+    run_mesos_start_master --port=5050 --zk=file://$zookeeper_standalone_master_url_file
+    run_mesos_start_slave file://$zookeeper_standalone_master_url_file
+    echo "Testing Spark on Mesos with Single Zookeeper Instance for fault tolerance...   "
+    ${spark_install_dir}/run spark.examples.SparkPi `cat $zookeeper_standalone_master_url_file` && local sparkOnMesosSingleZookeeper=$? && run_mesos_stop_cluster && stop_zookeeper_server ${zookeeper_confdir}/zoo_standalone.cfg
+    echo -n "${bold_text}Tested Mesos + Spark on Standalone Zookeeper instance...${normal_text}"
+    [ $sparkOnMesosSingleZookeeper == 0 ] && echo "${bold_text}[ PASSED ]${normal_text}" || echo "${bold_text}[ FAILED ]${normal_text}"
 
     #local zkflag_spark=zk://localhost:2181,localhost:2182,localhost:2183,localhost:2184,localhost:2185/znode 
     #local sparkResult=$(${spark_install_dir}/run spark.examples.SparkPi $zkflag_spark) # >& /dev/null && echo $?)   
@@ -444,9 +447,9 @@ config_spark() {
 test_spark() {
     # Test 1: Running a "local" version of Spark with 2 cores
     echo
-    echo -n "${bold_text}Test 1: Testing Spark in Local Standalone Mode${normal_text}"
+    echo -n "${bold_text}Test 1: Testing Spark in Local Standalone Mode...   ${normal_text}"
     local sparkResult=$(cd ${spark_install_dir} && ./run spark.examples.SparkLR local[2] >& /dev/null && echo $?) 
-    [ $sparkResult == 0 ] && echo "[ PASSED ]" || echo "[ FAILED ]"
+    [ $sparkResult == 0 ] && echo "${bold_text}[ PASSED ]${normal_text}" || echo "${bold_text}[ FAILED ]${normal_text}"
 }
 
 clean_spark() {
@@ -671,7 +674,7 @@ test_hadoop_standalone() {
     mkdir sandbox/input
     cp conf/*.xml sandbox/input
     bin/hadoop jar hadoop-examples-*.jar grep sandbox/input sandbox/output 'dfs[a-z.]+' >& /dev/null
-    [ -e sandbox/output/_SUCCESS ] && echo "[ PASSED ]" || echo "[ FAILED ]"
+    [ -e sandbox/output/_SUCCESS ] && echo "${bold_text}[ PASSED ]${normal_text}" || echo "${bold_text}[ FAILED ]${normal_text}"
     
     popd >& /dev/null
     rm -rf ${hadoop_install_dir}/sandbox
@@ -700,8 +703,8 @@ test_hadoop_pseudo_distributed() {
         ${hadoop_install_dir}/bin/hadoop fs -put ${hadoop_install_dir}/conf/local_distributed/* ${hadoop_work_dir}/input >& /dev/null
         # Fix hard-coding yo...
         ${hadoop_install_dir}/bin/hadoop jar ${hadoop_install_dir}/hadoop-examples-*.jar grep ${hadoop_work_dir}/input ${hadoop_work_dir}/output 'dfs[a-z.]+' >& /dev/null
-        echo -n "Tested Hadoop - Pseudo-Distributed Mode...   "
-        [ -e ${hadoop_work_dir}/output/_SUCCESS ] && echo "[ PASSED ]" || echo "[ FAILED ]"
+        echo -n "${bold_text}Tested Hadoop - Pseudo-Distributed Mode...   ${normal_text}"
+        [ -e ${hadoop_work_dir}/output/_SUCCESS ] && echo "${bold_text}[ PASSED ]${normal_text}" || echo "${bold_text}[ FAILED ]${normal_text}"
         ${hadoop_install_dir}/bin/hadoop fs -rmr ${hadoop_work_dir}/input >& /dev/null
         ${hadoop_install_dir}/bin/hadoop fs -rmr ${hadoop_work_dir}/output >& /dev/null
     
@@ -803,10 +806,12 @@ config_zookeeper() {
             mkdir ${zookeeper_workdir}/cluster_replication
 
             # Master URL file for replicated, standalone modes
-            local replicated_master_url_file=${zookeeper_confdir}/zoo_url_local_replicated.cfg
-            local standalone_master_url_file=${zookeeper_confdir}/zoo_url_standalone.cfg
-            rm $replicated_master_url_file
-            rm $standalone_master_url_file
+            if [ -e ${zookeeper_replicated_master_url_file} ]; then
+                rm $zookeeper_replicated_master_url_file
+            fi
+            if [ -e ${zookeeper_standalone_master_url_file} ]; then
+                rm $zookeeper_standalone_master_url_file
+            fi
 
             echo "Configuring Zookeeper for standalone local operation..."
             echo "tickTime=2000" >> ${zookeeper_confdir}/zoo_standalone.cfg
@@ -815,7 +820,7 @@ config_zookeeper() {
             echo "clientPort=$zookeeper_client_port" \
              >> ${zookeeper_confdir}/zoo_standalone.cfg
             echo "zk://localhost:$zookeeper_client_port/znode" \
-             >> $standalone_master_url_file
+             >> $zookeeper_standalone_master_url_file
 
             # This is a bit wordy...but what else to do? Engage beast mode! We
             # need a separate configuration for each locally replicated 
@@ -838,7 +843,7 @@ config_zookeeper() {
             local zk_datadir=${zookeeper_workdir}/local_replication/local
 
             # Initialize local replicated master url file
-            echo -n "zk://" >> $replicated_master_url_file
+            echo -n "zk://" >> $zookeeper_replicated_master_url_file
 
             for (( n=1; n <= $quorum_size; n++ ))
             do
@@ -872,14 +877,14 @@ config_zookeeper() {
                 done
             
                 # Add instance to replicated master URL file
-                echo -n "localhost:$nth_client_port" >> $replicated_master_url_file
+                echo -n "localhost:$nth_client_port" >> $zookeeper_replicated_master_url_file
                 if [ $n -lt $quorum_size ]; then
-                    echo -n "," >> $replicated_master_url_file
+                    echo -n "," >> $zookeeper_replicated_master_url_file
                 fi
             done
 
             # Add znode to Zookeeper file for local replicated Mesos here
-            echo "/znode" >> $replicated_master_url_file
+            echo "/znode" >> $zookeeper_replicated_master_url_file
 
             # TODO echo Configuring Zookeeper for cluster operation
             # This will be a lot like local replicated setup, except across
@@ -899,16 +904,15 @@ test_zookeeper() {
     start_zookeeper_server "${zookeeper_install_dir}/conf/zoo_standalone.cfg"
     ${zookeeper_install_dir}/bin/zkCli.sh -server 127.0.0.1:2181 ls / quit >& /dev/null
     zkret=$?
-    echo -n "Tested Zookeeper local standalone configuration...   "
-    [ $zkret == 0 ] && echo " [ PASSED ]" || echo " [ FAILED ]"
     stop_zookeeper_server "${zookeeper_install_dir}/conf/zoo_standalone.cfg"
+    echo -n "${bold_text}Tested Zookeeper local standalone configuration...   ${normal_text}"
+    [ $zkret == 0 ] && echo "${bold_text} [ PASSED ]${normal_text}" || echo "${bold_text} [ FAILED ]${normal_text}"
    
-    # Zookeeper test for locally replicated cluster 
-    echo
-    echo "${bold_text}Zookeeper Test 2: Local Replication Test${normal_text}"
-
-    echo -n "Tested Zookeeper Local Replication with N Quorum Members"
-    echo "[ TBD ]"
+    # TODO Zookeeper test for locally replicated cluster 
+    #echo
+    #echo "${bold_text}Zookeeper Test 2: Local Replication Test${normal_text}"
+    #echo -n "Tested Zookeeper Local Replication with N Quorum Members"
+    #echo "[ TBD ]"
 
     # TODO Cluster replication test
 }
@@ -1004,9 +1008,9 @@ setup_compute_tools() {
     echo "---------------------------------"
     echo " Installing Hadoop - Latest Stable Version"
     echo "---------------------------------"
-    #setup_hadoop
-    #config_hadoop   
-    #test_hadoop
+    setup_hadoop
+    config_hadoop   
+    test_hadoop
 
     echo
     echo "---------------------------------"
