Mesos non-fault-tolerant Spark test passes; slave configured

diff --git a/compute-tools/esg-compute-tools b/compute-tools/esg-compute-tools
--- a/compute-tools/esg-compute-tools
+++ b/compute-tools/esg-compute-tools
@@ -238,15 +238,21 @@ config_mesos() {
 
 test_mesos() {
     # Currently running Mesos + Zookeeper with custom deploy methods, tested here.
-    # Test 1: Mesos + Spark
-    # Test 2: Mesos + Hadoop
-    # Test 3: Mesos + Hadoop + Spark
-    
+    # Test 1: Mesos + Spark, Standalone 
+    # Test 2: Mesos + Spark with Quorum Management
+     
     echo
-    echo "Test 1: Mesos with Spark Framework, [TODO Zookeeper Quorum Management]"
-    run_mesos_stop_cluster
-    stop_mesos_zookeeper
-    start_mesos_zookeeper
+    echo "Test 1: Mesos with Spark Framework, Standalone (Fault-Tolerance Mode Disabled)"
+    run_mesos_start_master --port=5050
+    local standaloneMesosMasterURL=$(get_config_ip eth0):5050
+    run_mesos_start_slave $standaloneMesosMasterURL
+    echo "Testing Spark on Mesos..."
+    ${spark_install_dir}/run spark.examples.SparkPi $standaloneMesosMasterURL >& /dev/null && sparkOnMesosStandalone=$? && run_mesos_stop_cluster
+    echo -n "Tested Mesos (non-fault-tolerant) with Spark...   "
+    [ $sparkOnMesosStandalone == 0 ] && echo "[ PASSED ]" || echo "[ FAILED ]"
+
+    #stop_mesos_zookeeper
+    #start_mesos_zookeeper
     
     # TODO Yuck hard-coding
     #local zkflag_spark=zk://localhost:2181,localhost:2182,localhost:2183,localhost:2184,localhost:2185/znode 
@@ -254,21 +260,21 @@ test_mesos() {
     #echo -n "Tested Mesos Local Cluster with Spark...   "
     #[ $sparkResult == 0 ] && echo "[ PASSED ]" || echo "[ FAILED ]"
     
-    run_mesos_stop_cluster
-    stop_mesos_zookeeper
+    #run_mesos_stop_cluster
+    #stop_mesos_zookeeper
 
-    echo
-    echo "Test 2: Mesos with Hadoop Framework, [TODO Zookeeper Quorum Management]"
+    #echo
+    #echo "Test 2: Mesos with Hadoop Framework, [TODO Zookeeper Quorum Management]"
     # Starts Zookeeper, starts Mesos, runs Hadoop pseudo-distributed test job on Mesos
     # TODO Starts Zookeeper
-    echo -n "Tested Mesos Local Cluster with Legacy Hadoop...   "
-    echo "[ TBD ]"
+    #echo -n "Tested Mesos Local Cluster with Legacy Hadoop...   "
+    #echo "[ TBD ]"
 
-    echo
-    echo "Test 3: Mesos with Hadoop, Spark, and [TODO Zookeeper Quorum Management]"
+    #echo
+    #echo "Test 3: Mesos with Hadoop, Spark, and [TODO Zookeeper Quorum Management]"
     # Starts Zookeeper, starts Mesos, runs Spark job and Hadoop job on mesos
-    echo -n "Tested Mesos Local Cluster with Hadoop, Spark...   "
-    echo "[ TBD ]"
+    #echo -n "Tested Mesos Local Cluster with Hadoop, Spark...   "
+    #echo "[ TBD ]"
 
 }
 
@@ -308,7 +314,7 @@ run_mesos_start_master() {
     # TODO Start with Zookeeper URL, ESGF IP address
     echo "Starting Mesos Master"
     ${mesos_build_dir}/bin/mesos-master.sh --quiet $@ &
-    [ $? == 0 ] && echo "[ Mesos Master now running ]" || echo "[Mesos Master failed to run]"  
+    [ $? == 0 ] && echo "[ Mesos Master now running ]" || echo "[ Mesos Master failed to run ]"  
 }
 
 run_mesos_start_slave() {
@@ -316,7 +322,8 @@ run_mesos_start_slave() {
     # TODO figure out correct memory resources
     echo "Starting Mesos Slave"
     local mesos_master_url=$(get_config_ip eth0)
-    ${mesos_build_dir}/bin/mesos-slave.sh "--master=$1" "--resources=cpus:2;mem:1024" &
+    ${mesos_build_dir}/bin/mesos-slave.sh --quiet --master=$1 "--resources=cpus:2;mem:1024" &
+    [ $? == 0 ] && echo "[ Mesos Slave now running ]" || echo "[ Mesos Slave failed to run ]" 
 }
 
 run_mesos_stop_cluster() {
@@ -972,17 +979,17 @@ setup_compute_tools() {
     echo "---------------------------------"
     echo " Installing Hadoop - Latest Stable Version"
     echo "---------------------------------"
-    setup_hadoop
-    config_hadoop   
-    test_hadoop
+    #setup_hadoop
+    #config_hadoop   
+    #test_hadoop
 
     echo
     echo "---------------------------------"
     echo " Installing Zookeeper"
     echo "---------------------------------"
-    setup_zookeeper
-    config_zookeeper
-    test_zookeeper
+    #setup_zookeeper
+    #config_zookeeper
+    #test_zookeeper
 
     echo
     echo "---------------------------------"
@@ -996,9 +1003,9 @@ setup_compute_tools() {
     echo "---------------------------------"
     echo " Installing Spark"
     echo "---------------------------------"
-    setup_spark
-    config_spark
-    test_spark
+    #setup_spark
+    #config_spark
+    #test_spark
 }
 
 if [[ "$BASH_SOURCE" == "$0" ]]
